
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2011-09
  :PROPERTIES:
  :PAGE:     ing/2011-09.html
  :ARCHIVE_TIME: 2014-01-11 六 14:20
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. How do I control how [Emacs] makes backup files?  http://is.gd/weMaLG [2011-09-01 16:20:20]
2. [firefox] OmniSidebar这个扩展很爽，你可以得到两个sidebar，而且可以设置为auto-hide方式
   https://addons.mozilla.org/zh-CN/firefox/addon/omnisidebar/ [2011-09-01 16:51:24]
3. [emacs] WhichFuncMode is based on ImenuMode，如果which-func工作不正常的话，很可能就是semantic搞
   乱了imenu-create-index-function [2011-09-01 17:50:20]
4. 这里说Firefox 5吃内存太多的一个原因是CSS错误信息太多，在about:config里面将
   layout.css.report_errors设为false就好了
   http://heaven.branda.to/~thinker/GinGin_CGI.py/show_id_doc/454 [2011-09-02 14:25:08]
5. [emacs] easymenu的用法简介 http://emacs-fu.blogspot.com/2009/04/adding-custom-menus.html
   [2011-09-02 14:31:43]
6. [android] Automatically Dim Your Phone's Brightness in the Morning with Tasker
   http://is.gd/I3Xwrt [2011-09-02 14:55:50]
7. [emacs] (setq-default require-final-newline ”ask” use-dialog-box nil
   ediff-window-setup-function 'ediff-setup-windows-plain) [2011-09-02 19:11:47]
8. [emacs][xml] hl-tags-mode Emacs minor mode for highlighting HTML start and end tags
   https://github.com/deactivated/hl-tags-mode [2011-09-02 19:28:31]
9. [shell]dd时显示进度 dd bs=1M if=/dev/sr0 of=openSUSE-11.3-DVD-i586.iso & pid=$! <CR> while
   1; do kill -USR1 $pid && sleep 5 || break; done [2011-09-05 09:14:27]
10. [工具软件] 测试了一下谷歌拼音2.6的语音输入，识别率不高啊，难道真是因为俺的普通话不标准？
    [2011-09-05 12:52:18]
11. [工具软件] DropIt is a simple floating target image on your desktop you can drag-and-drop
    files onto to quickly process them with a predefined action [2011-09-05 13:37:09]
12. freepascal 的社区太古旧了，只有mailing list和wiki，连news也没有rss，也没有类似planet的东西——大
    家去哪里分享好的内容/想法呢？ [2011-09-06 08:46:11]
13. 都说Pearl harbour是“ 珍珠港”的意思，其实还有更中土的翻译： 蚌埠；都说Greenland是“格陵兰”的
    意思，其实还有更中土的翻译：青岛。http://is.gd/Chuxdu [2011-09-06 09:24:47]
14. [emacs] (eval-after-load ”vc” '(remove-hook 'find-file-hooks
    'vc-find-file-hook)) [2011-09-06 16:56:45]
15. [emacs] tabbar-ruler 在emacs 23.1上不能工作(并且*Message*中老报告settting-constant什么什么
    的)，v24上没有问题，还没查是怎么回事 [2011-09-06 17:59:57]
16. [todo] emacs-env: message/error; misc: -viper, +backup; foobar: +fuzzy, +second-sel
    [2011-09-06 18:07:01]
17. 有没有第三方的插件可以在[Delphi] 7/2010上实现Document Insight的功能啊？期望这样的功能好久了
    http://www.cnblogs.com/zzzl/archive/2011/09/06/2165939.html [2011-09-07 08:21:26]
18. [delphi] 搜到DevJet有一个这样的插件 Documentation Insight，不过不是免费的 :-(
    http://www.devjet.net/products/documentation-insight/ [2011-09-07 08:26:56]
19. [emacs][vim] Ex command for Emacs http://www.advogato.org/person/chalst/diary/277.html
    [2011-09-07 16:25:09]
20. [emacs][vim] 续: viper里面有哪些Ex命令可以用？可以查它的文档 http://is.gd/SDta9f (gnu.org)
    [2011-09-07 16:58:06]
21. [emacs] M-5 M-< 可以跳到全buffer的50%处，M-1 M->跳到倒数10%处 Moving To An Intermediate
    Point In An Emacs Buffer http://irreal.org/blog/?p=245 [2011-09-08 08:48:52]
22. [todo][emacs][vim] wget
    http://svn.sv.gnu.org/svn/emacswiki/emacswikipages/VimMode_-_User%27s_Guide [2011-09-08
    10:36:55]
23. [cygwin][emacs] (add-to-list 'woman-manpath (expand-file-name ”usr/share/man”
    cygwin-root-path)) [2011-09-09 12:53:06]
24. [firefox] 根据Emacs 24里自带tango-dark-theme配的color toggle颜色: fg:#eeeeec bg:#2e3436
    link:#edd400 visited link:#8ae234 [2011-09-12 21:32:42]
25. [firefox][chrome]『open in chrome』open all firefox tabs in chrome from tool menu
    http://is.gd/asELrb [2011-09-13 07:46:35]
26. [emacs] 一直对drag-stuff-left/right（或者说transpose-words）的行为不满意(two-words会变成
    wordstwo-而不是words-two），刚才查了一下原来Emacs缺省是没有问题的，而我这里的问题是
    hideshowvis.el引入的 [2011-09-13 18:03:30]
27. [emacs] 续上: 单独打开hs-minor-mode没有问题，但再打开hideshowvis-minor-mode就出问题了，而且出问
    题之后要把hideshowvis-m-m和hs-m-m都关掉才正常，再单独打开hs-m-m又不行了 [2011-09-13 18:08:00]
28. [emacs] 其实我早知道mark与point之间构成一个region，但一直用cua-mode/transient-mark-mode，习惯了
    shift的选择方式，而mark+point方式相对不直观，就很少用了 [2011-09-14 11:58:01]
29. [emacs] 续: 但如果知道mark在什么位置的话，可以减少不少移动光标的操作，具体措施有两
    条：visible-mark.el提供的visible-mark-mode, 以及C-SPC C-SPC (连按两次可以避免激活选区)，更好的
    办法是：http://is.gd/QTb9v9 [2011-09-14 13:09:09]
30. VirtualBox 没用几天，所有的虚拟机都起不来了，都报 kernel panic - not syncing: Attempted to
    kill idle task! (出错的都是linux, 而那个android-x86则没有问题) [2011-09-15 10:12:46]
31. [firefox] 根据color-theme-tangotango配的color toggle颜色: fg:#eeeeec bg:#2e3436 link:#729fcf
    visited link:#ad7fa8 [2011-09-15 12:59:17]
32. [emacs] devel-notes.el - Add annotation to sources and track them in an org file.
    http://www.emacswiki.org/emacs/DevelockMode [2011-09-15 17:46:23]
33. [g_f_w] 在天朝，搞点技术真是不易啊，打算装一个Chef来体验一下，手册上让我去
    http://rubyinstall.org 下载ruby安装包，但这个网站怎么都打不开。我心想这不会是被墙了
    吧，python.org都被墙过，别说这个不会，我用手机一搜，还真是，TNND! [2011-09-15 17:55:46]
34. [emacs] one-key.el #1261 添加一个换行, 改为insert(”\n))\n\n”) [2011-09-15 18:22:50]
35. [emacs] Integrating speedbar in the ECB frame
    http://ecb.sourceforge.net/docs/Integrating-speedbar.html﻿ [2011-09-16 10:03:45]
36. Locating [firefox]'s profile folder (v3.6+) : Help->Troubleshooting
    Information->Application Basic->Open Containing Folder [2011-09-16 10:04:48]
37. [☆] Using Winhlp32 to call a Help File
    http://support.asna.com/kb/documentation/Help_Files/AVR40/AVR/Using_Winhlp32.htm [2011-09-16
    11:54:11]
38. [☆] Mousewheel Click to Paste in Firefox
    http://lifehacker.com/353036/mousewheel-click-to-paste-in-firefox [2011-09-16 14:17:59]
39. [☆][emacs] How do I control how Emacs makes backup files? - Stack Overflow
    http://is.gd/weMaLG [2011-09-16 14:31:19]
40. [☆][emacs] alien technology http://kanis.fr/nterm.html [2011-09-16 15:09:15]
41. [☆][emacs][shell] EmacsWiki: Eshell Redirection
    http://www.emacswiki.org/emacs/EshellRedirection [2011-09-16 15:11:10]
42. [☆][emacs] “winner-mode”: Preserve Your Split-Panes Configulation
    http://xahlee.blogspot.com/2011/08/emacs-winner-mode-preserve-your-split.html [2011-09-16
    15:12:31]
43. [☆][unix][cli] Awesome but often unknown Linux commands and tools: pgrep/pkill, htop, mytop,
    lsof, iptraf http://is.gd/il9P20 [2011-09-16 15:14:17]
44. [android] (qemu模拟arm) 模拟器太慢？有多少人试过用Android-x86来做应用开发啊? (from CSDN)
    http://is.gd/sc3gjE [2011-09-16 15:27:19]
45. [emacs][todo] ediff-split-window-function http://www.emacswiki.org/emacs/EdiffMode [2011-09-16
    18:01:30]
46. [emacs] logviewer-mode of emacs
    http://www.cnblogs.com/yangyingchao/archive/2011/09/16/2178364.html [2011-09-16 18:16:18]
47. [firefox] showcase: show tabs as thumbnails
    https://addons.mozilla.org/en-US/firefox/addon/showcase/ [2011-09-18 20:32:11]
48. [totalcmd] Total Commander 8 beta 1: 发布纯64位版本，改进重命名搜索等功能 - 善用佳软
    http://xbeta.info/tc8.htm [2011-09-19 09:40:31]
49. 哈哈, 好玩: 『…翻译是一门艺术..真的』http://blog.sina.com.cn/s/blog_5e9f35ea0102dubp.html
    [2011-09-19 09:56:50]
50. 『iStarin.com 電影海報換你當主角，三步驟免費線上合成 - 電腦玩物』
    http://feedproxy.google.com/~r/playpc/~3/-4NKEc7iXLQ/istarincom.html [2011-09-19 09:57:45]
51. [emacs][vim] 续: viper里面有哪些Ex命令可以用？可以用C-h v察看ex-token-alist (它在viper-ex.el中)
    [2011-09-20 06:54:41]
52. Delphi uses Free Pascal for their iPad support ?
    http://www.lazarussupport.com/lazarus/weblog/delphi-uses-free-pascal-for-ipad-support
    [2011-09-21 09:07:07]
53. [工具软件] UltraExplorer配合上FileMenuTools和TeraCopy/SuperCopier，以及Total Commander 的wlx插
    件，感觉也很不错 [2011-09-21 15:37:11]
54. Programming Clojure Beta Nov.2008 (pdf) http://download.csdn.net/detail/kittyjie/800268
    [2011-09-21 15:44:06]
55. [Emacs] workgroups-el: manage window layout & configs https://github.com/tlh/workgroups.el
    [2011-09-22 07:30:35]
56. [linux] 还真有多tab风格的窗口管理器（而且是用gtk的） partiwm http://code.google.com/p/partiwm/
    不过09年11月之后就没有新版本了 [2011-09-22 09:09:44]
57. [delphi][ios] 啥是FireMonKey? 『Firemonkey，下一代业务程序平台 - 移动开发 - ITeye资讯』
    http://www.iteye.com/news/22707 [2011-09-22 10:50:49]
58. 本来说短期内不再学习编程语言了的，但我决定现在开始再学一门: Clojure http://clojure.org/
    [2011-09-22 10:51:11]
59. Clojure on CLR/DLR - Clojure | Google 网上论坛
    http://groups.google.com/group/clojure/browse_thread/thread/54571c9b8f625dba/1198026ac0a62917
    [2011-09-22 14:58:04]
60. 转: 在北京的官场上，老婆孩子全在中国的，搞不好只有骆家辉一个人…… [2011-09-22 16:02:07]
61. [emacs] M-x recover-this-file又救了我，好几百字找回来了 [2011-09-23 14:00:09]
62. InfoQ: 领域驱动设计精简版 - http://www.infoq.com/cn/minibooks/domain-driven-design-quickly
    [2011-09-23 14:07:44]
63. windows下如果想直接在Emacs里阅读pdf的话，需要libpng-xx.dll和gs.exe, 它的doc-view-mode是通过用
    gs将pdf转换为png来实现的 [2011-09-23 15:29:28]
64. libpng-xx.dll: 对Emacs 23.1而言，需要的是libpng12.dll或者libpng13.dll，前者可以从
    http://gnuwin32.sf.net 下载到（后者不知道从哪里找） [2011-09-23 15:32:36]
65. 续: libpngxx.dll: 对Emacs 24.0，需要的是libpng14-14.dll 或者libpng14.dll，前者可以从gnome站点下
    载到 http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/ 后者也不知道 [2011-09-23
    15:33:36]
66. 续: gs.exe: 从 http://sourceforge.net/projects/ghostscript/files/GPL%20Ghostscript/ 下载，然后
    将gswin32c.exe改名为gs.exe，那个dll也是需要的，其它文件可以删除 [2011-09-23 15:35:22]
67. presentation/ppt真不是什么好东西，层次不清，很多内容在文档之外，《Joel谈软件开发》里面选了一篇
    文章来说这个问题: PowerPoint Remix PowerPoint Remix http://www.aaronsw.com/weblog/000931
    [2011-09-24 13:05:00]
68. 续: 一个例子是我在看这篇Clojure-v2.pdf http://is.gd/xpt6w2 ，中间讲并发的部分看得稀里糊涂的，看
    IBM dw这篇『Clojure与并发性』一下就看明白了 http://is.gd/UOssXQ [2011-09-24 13:16:50]
69. [firefox] splitpanel扩展禁止将拖拽到内容区的文字做为网址(仍然可以拖到其工具栏上): overlay.js中
    browser()函数里，注释掉后面8行 //if (window.nsDragAndDrop) ... [2011-09-24 17:23:48]
70. [unix][shell] atool is a script for managing file archives of various types (tar, tar+gzip,
    zip, bzip2, rar, 7zip, ...): aunpack/apack/als http://www.nongnu.org/atool/ [2011-09-24
    17:39:44]
71. [firefox] 下面这些扩展会被palemoon自动删除(至少5.0是这样)，要改放到app目录下（不要放在用户目录）
    feedly, feedbar, pano, scrapbookplus, splitpanel, toggleproxy [2011-09-24 18:01:11]
72. [evernote] 家里已导出并更新到公司的，截止至Aug 07, 2011 [2011-09-24 18:05:01]
73. [emacs] Fuzzy Search In Emacs -
    http://splash-of-open-sauce.blogspot.com/2010/10/fuzzy-search-in-emacs.html [2011-09-25
    20:58:22]
74. 看人家这Emacs配的，屏幕不大玩不转啊
    http://dl.iteye.com/upload/attachment/559645/87866b6d-47da-3f7e-857f-1ab861f40290.png
    [2011-09-26 09:11:55]
75. [emacs] Putting it in Perspective http://nex-3.com/posts/72-putting-it-in-perspective 跟tabbar
 不同的是，tabbar只切换当前window的buffer，perspective切换整个frame内的window和buffer [2011-09-27
 08:45:45]
76. [emacs] 不过用了一会儿觉得这个perspective跟tabbar有点冲突啊（不是功能上的冲突，是用户体验上
    的），得想法改改tabbar的group方法，将两者协调起来 [2011-09-27 08:46:51]
77. [emacs] 这个perspective功能上跟elscreen有点象(可能没它强，毕竟elscreen是个大包，有好多个文件)，
    只不过elscreen跟tabbar抢header-line [2011-09-27 09:02:48]
78. 有意思: IKVM.NET is an implementation of Java for Mono and the Microsoft .NET
    Framework. [2011-09-27 09:20:37]
79. InfoQ这次改版好啊，终于不用hack css来实现内容区足够宽了（何况只有firefox和opera支持user css）
    [2011-09-27 09:45:09]
80. 翻-墙 Opera Mini (java，android，blackberry) 下载 http://goo.gl/JYHjr [2011-09-28 18:28:33]
81. [firefox] 将地址栏恢复成传统样式：在about:config里将browser.urlbar.trimURLs和
    browser.urlbar.formatting.enabled 都设置为false [2011-09-28 20:05:44]
82. [shell] grep的两个替代方案: 1)ack会自动忽略CVS,.svn这些目录和备份文件、二进制文件，缺省就递归搜
    索子目录，可指定按编程语言搜索。ack用perl写的 http://betterthangrep.com/ [2011-09-29
    13:50:00]
83. [shell] grep的两个替代方案: 1)glark 支持多个关键字，并且可指定两者之间最多间隔几行；与ack相同的
    是可高亮要找的关键字，缺省不搜索二进制文件，支持pcre。不过是用ruby写的，要装ruby
    http://www.incava.org/projects/glark [2011-09-29 14:33:16]
84. [emacs] 多窗口布局管理，我应该用哪个呢？ elscreen, escreen, perspective, workgroups
    [2011-09-29 18:25:18]
85. [2evernote] How to build [python] extensions with [mingw] (without installing Visual Studio
    200x crap) http://www.mingw.org/wiki/FAQ#toc14 [2011-09-30 13:12:18]
86. 想用mingw编译perl模块真是太麻烦了，折腾了好久没搞定，好在最后发现ActiveState提供了编译好的二进
    制包，用ppm工具进行安装 http://ppm4.activestate.com/ [2011-09-30 13:26:22]
87. [perl] strawberry perl也支持PPM和PAR via 『Perl Win32 Distributions』 http://is.gd/TCDE73
    [2011-09-30 13:31:24]
88. [mingw] 跟VC的动态库链接时需要这些工具:reimp, pexports, res2coff，它们都在mingw-utils这个包里
    [2011-09-30 13:34:39]
89. [mingw] 总算有个包安装/升级工具了: mingw-get install mingw-utils
    http://sourceforge.net/projects/mingw/files/Automated%20MinGW%20Installer/mingw-get/
    [2011-09-30 13:48:22]
90. [mingw] 跟VC的动态库链接时需要这些工具:reimp, pexports, res2coff，它们都在mingw-utils这个包里，
    不过mingw网址的下载目录实在是混乱啊，谁能猜到mingw-utils在这个位置: http://is.gd/eDq5pI
    [2011-09-30 13:52:07]
91. [2evernote] mingw-utils包内容介绍 http://olex.openlogic.com/packages/mingw-utils [2011-09-30
    13:55:52]
92. [perl] Strawberry Perl 这个版本好像不是用VC编译的，而是用mingw
    http://win32.perl.org/wiki/index.php?title=Strawberry_Perl [2011-09-30 13:56:44]


