
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2011-02
  :PROPERTIES:
  :PAGE:     ing/2011-02.html
  :ARCHIVE_TIME: 2014-01-11 六 14:20
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. 因不堪6个版本并行, #debian 的 #ruby 包维护者撂挑子了 RT @bamanzi: [GR] On the maintainability
   of Ruby http://bit.ly/e4LCOo [2011-02-01 06:50:00]
2. [RIL][linux] Cross-distro Meeting on Application Installer
   http://distributions.freedesktop.org/wiki/Meetings/AppInstaller2011 [2011-02-01 08:42:14]
3. [FAR] multipanel (http://farplugins.sf.net ) 不如paneltabs (http://far-plugins.googlecode.com )
   直观方便 [2011-02-01 10:06:44]
4. [FAR] TempPanel老丢记录，HotDir用起来又不方便，干脆还是用回外部工具FavMenu了。不过刚发现FAR的自
   动完成对FavMenu的输入有影响，SetKeyDelay 30后没有问题了 [2011-02-01 11:00:21]
5. [FAR][addons] 玩Panel Color没成功 http://code.google.com/p/panel-colorer/ [2011-02-01
   11:21:47]
6. [emacs][theme] Naquadah theme
   http://julien.danjou.info/blog/index.html#Naquadah_theme_for_Emacs [2011-02-01 12:04:07]
7. [emacs][orgmode] 听了一下Google Tech Talk on Emacs Org-mode（昨天从youku下载的)，发现自己现在英
   文听力提高了不少——难道是最近几个月看英美剧集的结果？ [2011-02-01 15:17:17]
8. [dropbox] RT @laoyang945: [GR]為什麼 Dropbox 大成功，Syncplicity 卻沒有 - - 香港矽谷
   http://goo.gl/4jgaZ [2011-02-01 18:48:20]
9. [debian][RIL] RT @debian: Learn how to keep your #Debian system clean by removing useless
   configuration files http://bit.ly/ggCiVm [2011-02-01 18:56:50]
10. [mmedia] 豆瓣电台桌面版——使用说明图文版 - 拖鞋的工具箱 - 博客大巴
    http://slippor.blogbus.com/logs/62644175.html [2011-02-01 21:28:57]
11. [vim] Refining search patterns with the command-line window http://is.gd/3ApCbM [2011-02-01
    21:32:14]
12. [unix][shell][RIL] Using zsh http://jbw.cc/2010/07/20/using-zsh/ [2011-02-01 21:34:39]
13. [emacs][addons] Textmate minor mode http://ozmm.org/posts/textmate_minor_mode.html [2011-02-01
    21:43:55]
14. [emacs][geek] RT @echoes2099: #emacs keyboard shortcuts in Microsoft Word. U heard
    right! #vbacs #linux http://tinyurl.com/5rqt494 [2011-02-02 13:06:47]
15. [emacs]RT Latest #emacs trunk code changes the way mouse & X11 pasting works. Read this thread
    if you want the old setup http://ur1.ca/32o1j [2011-02-02 13:56:48]
16. [devtools] RT @ingramchen: Desktop JSON Editor / Viewer / Formatter http://www.jsonpad.co.cc/
    [2011-02-02 14:14:43]
17. 如果有一天，我老无所依，请把我留在，新闻联播里 [2011-02-03 08:42:38]
18. [工具软件][RIL] RT @appinn: avast! Free Antivirus 6.0 免費防毒軟體中文新版下載與試用心得
    http://bit.ly/hJxakQ [2011-02-03 09:10:07]
19. [Firefox][RIL] RT @esorhjy: GreaseMonkey 10+1個私房推薦腳本：讓網頁變好用的 Firefox 套件
    http://j.mp/f1iunm [2011-02-03 09:11:24]
20. RT @chon219: 祝大家在以后的日子里，男生象Oracle般健壮；女生象Ubuntu般漂亮；桃花运象IE中毒般频
    繁；钱包如Gmail容量般壮大；升职速度赶上微软打补丁；追女朋友像木马一样猖獗；生活像重装电脑后一样
    幸福；写程序敲代码和聊天一样有激情。祝大家新年快乐！ [2011-02-03 09:12:59]
21. 今早这里人真少啊，看来大家的年过得都挺热闹啊 [2011-02-03 09:30:17]
22. [tips] 下载土豆视频的最简单方法: http://www.kisstudou.com 只要在土豆网播放视频时在地址栏的
    tudou.com变成kisstudou.com就可以下载了!  [2011-02-05 11:24:17]
23. [emacs][video] 上传了一份emacs-cua-rect.flv到土豆网，我从vimeo.com下载的
    http://www.tudou.com/programs/view/He4etr8Q5Ag/ [2011-02-05 17:26:29]
24. RT @debian: There will be #squeeze release parties around the world today. Find one near you at
    http://wiki.debian.org/ReleasePartySqueeze o [2011-02-05 18:07:50]
25. RT @debian: The release has now begun! As a first step the cron jobs on the FTP master have now
    been disabled in order to be able to work un [2011-02-05 18:08:45]
26. [emacs] GNU Emacs 24提供了describe-package命令, 应该比那个finder-commentary好记一些 [2011-02-05
    21:15:06]
27. RT @debian: #debian final test results are coming in, nearing the final mirror push
    ... #squeeze [2011-02-06 07:54:51]
28. [emacs][RIL] Key Binding Conventions http://is.gd/qy9grg [2011-02-06 08:50:34]
29. [RIL] http://tw.myblog.yahoo.com/blue-comic/article?mid=760&prev=761&next=757 [2011-02-06
    22:17:21]
30. [emacs][RIL][python] RT @xah_lee: Unicode Support
    in #Ruby #Perl #Python #javascript #Java #Emacs Lisp #Mathematica http://goo.gl/f3fDW
    [2011-02-07 08:07:57]
31. 【奥斯卡提名-最佳影片】1.《黑天鹅》 2.《127小时》 3.《斗士》 4.《盗梦空间》 5.《问题不在孩子》
    6.《国王的演讲》7.《社交网络》 8.《玩具总动员3》 9.《大地惊雷》 [2011-02-07 10:53:24]
32. [RIL][工具软件]
    http://gnuser.wordpress.com/2007/12/31/setting-up-a-dict-dictionary-server-on-debian/
    [2011-02-07 11:56:42]
33. 王垠: 可直接到 dict.org 的 ftp 下载 转换好的字典 dz 文件就行了 ftp://ftp.dict.org/pub/dict/pre
    [2011-02-07 12:19:30]
34. [工具软件] 免费的bat2exe转换软件 http://www.f2ko.de/programs.php?lang=en&pid=b2e
    [2011-02-07 15:13:10]
35. [工具软件] 不需要dotNet的键盘映射工具 KeyTweak http://webpages.charter.net/krumsick/ (而
    SharpKeys/MapKeyboard都需要） [2011-02-07 16:25:51]
36. RT @debian: RT @zack: “Why #Debian matters more than ever” http://ur1.ca/3555x covers some
    arguments from my recent #DPL talks… and more! | [2011-02-08 07:14:29]
37. [debian][vs][ubuntu][mint] RT @debian: RT @zack: “Why #Debian matters more than ever”
    http://ur1.ca/3555x [2011-02-08 07:16:14]
38. [debian][vs][ubuntu] RT @schestowitz: Joining the fray: Why #Debian matters http://ur1.ca/358gn
    more responses to @sjvn disagreeing with the [2011-02-08 07:26:36]
39. [debian][vs][ubuntu] "Over time I realized I need stability more than newest packages". RT
    @schestowitz: Sweet Six: Falling In Love With #De [2011-02-08 07:34:09]
40. [debian][vs][ubuntu] RT @schestowitz: Sweet Six: Falling In Love With #Debian , Again
    http://ur1.ca/358f6 ... [2011-02-08 07:35:06]
41. [debian] Feb 6: RT @debian: #debian Migration of packages to testing has also been
    re-enabled: #wheezy just got 2306 new packages! [2011-02-08 07:43:53]
42. [debian] 新版发布的意义就在于testing又可以向前冲了:-) 不过还没看见iceweasel 3.6的影子:-( RT
    @debian: ... #wheezy just got 2306 new packages! [2011-02-08 07:53:01]
43. RT @jmtd: #debian holy crap, 434 packages in the NEW queue!
    http://ftp-master.debian.org/new.html [2011-02-08 07:57:41]
44. [colinux][debian] when #colinux will release pre-installed disk image of #debian 6?  though
    base system only, it would save me a lot of time [2011-02-08 08:06:08]
45. [2km] 深圳地铁线路图（一号线、二号线、三号线、四号线、五号线）线路图及详细站名
    http://bbs.zsjdc.com/theme-46869.html [2011-02-08 09:31:37]
46. [debian][tips] Debian Cleanup Tip #2: Get rid of obsolete packages http://bit.ly/dXGRRD When
    you upgrade, it's a good time to get rid of obs [2011-02-08 18:14:26]
47. [debian][tips] RT @jbfavre: Simple #Debian backports creation
    http://wiki.debian.org/SimpleBackportCreation [2011-02-08 18:15:47]
48. [emacs][iphone] 不知道怎么解决“脚踏板”问题的，难道是用ssh连上去运行？RT @basimple: #Emacs for
    iPhone http://gamma-level.com/iphoneos/ports/emacs [2011-02-08 18:40:34]
49. [emacs][RIL] Elisp Lesson: Execute/Compile Current File http://is.gd/D7rLXH [2011-02-08
    22:55:11]
50. [devtools] 极小巧的Diagram Designer http://meesoft.logicnet.dk/DiagramDesigner/ [2011-02-09
    09:19:09]
51. 春节打算写6篇博文的，大致内容都想好了，但只完成了两篇；想看的《绝望的主妇第六季》一集没看，《黎
    明之前》就看了两集，其它的就只看了一集Fringe S03EP10——而且也去什么地方玩，念叨了一年去爬小区后面
    的山也没去，这假期过的 [2011-02-09 10:34:50]
52. [TODO]琢磨一下用dict替代stardict(也再找找哪里可以方便地下载stardict词典) [2011-02-09 11:22:23]
53. [firefox][addons] 常用扩展 ScirbeFire https://addons.mozilla.org/en-US/firefox/addon/1730
    [2011-02-09 11:40:00]
54. [firefox][addons] 常用扩展 DownThemAll!  https://addons.mozilla.org/en-US/firefox/addon/201
    [2011-02-09 11:41:11]
55. [firefox][addons] 常用扩展 Firefox Sync https://addons.mozilla.org/en-US/firefox/addon/10868
    [2011-02-09 11:42:24]
56. [firefox][addons] 常用扩展 lastpass https://addons.mozilla.org/en-US/firefox/addon/8542
    [2011-02-09 11:43:17]
57. [firefox][addons] 常用扩展 unmht https://addons.mozilla.org/en-US/firefox/addon/8051
    [2011-02-09 11:44:33]
58. [firefox][addons] 常用扩展 Read It Later https://addons.mozilla.org/en-US/firefox/addon/7661
    [2011-02-09 13:25:53]
59. [emacs][RIL] RT @doitian: Mickey Petersen: Mastering Key Bindings in #Emacs
    http://bit.ly/dGC6vp [2011-02-09 13:48:59]
60. [dropbox][TODO] http://search.download.csdn.net/search/dexplore [2011-02-09 18:01:26]
61. [todo] 老婆说想喝奶茶了 [2011-02-09 22:29:45]
62. 突然发现 sourceforge.net 的项目页面变得简洁清爽了，比如 http://sf.net/projects/curl/
    [2011-02-10 09:05:47]
63. [emacs][xml] RT @stickster: @jsmith #Emacs for #XML editing write-up is here:
    http://ur1.ca/363ts Similar automation for #vim exists, you or [2011-02-10 09:39:49]
64. [工具软件] 一直在用的notepad2中文版是基于notepad2-mod 4.1的，前一段时间发现似乎有搜索文本时不能
    忽略大小写的bug（大小写不对就搜不到），刚才我确认了，而原版和mod-4.0上面都没有此问题。但4.0.x不
    能用注册表方法替换notepad [2011-02-10 15:01:34]
65. [工具软件] 打算使用Disk Explorer 替代以前用的WhereIsIt了，毕竟后者不是免费的，而且前者有TC插件
    http://depro.tjelinek.com/ [2011-02-10 16:40:40]
66. [firefox][addons] 常用扩展 Readability (id: 46442)
    https://addons.mozilla.org/en-US/firefox/addon/readability/ [2011-02-10 17:58:24]
67. [工具软件] 续: 试了一下notepad2-mod 4.1，确认没有该问题了。于是用它替换系统“记事本”，不过是英
    文版。 [2011-02-11 08:49:45]
68. [工具软件] notepad2-mod 相对原版多了代码折叠、书签功能，多了一些语言的语法高亮 BTW: 它现在放到了
    googlecode上: http://code.google.com/p/notepad2-mod/ [2011-02-11 08:51:53]
69. [工具软件] `whereis' from Joseph M. Newcomer 支持注册表里App Paths [2011-02-11 17:56:15]
70. [emacs][geek] RT @samdonnelley: #Emacs Reference Mug by rudzitis.org - Awesome way to keep
    caffeinated and ...  http://is.gd/CTKhe2 [2011-02-11 23:02:18]
71. [工具软件] 原来xkeymacs自带键盘映射功能，只是以前摸索时没看懂那个界面是怎么使用的，印像就不深
    了，今天才发现是在上方键盘图里拖动一个键到另一个键上 [2011-02-12 10:25:15]
72. [工具软件][emacs] 哈哈，我把Caps Lock映射成了App，这样我的emacs里面左右都有hyper键了 (为了以防万
    一，还是保留了Caps Lock，放在了右Windows键上） [2011-02-12 14:16:32]
73. [工具软件] 发现xkeymacs有bug, 某些应用程序上即使配置了成了disabled，但切换过去并不能做到自动禁
    用，目前发现Emacs容易出问题，下载了源代码，明天调一下 [2011-02-13 22:44:29]
74. 续: 在源代码中打开CUtils:Log跟踪了一下，发现GNU Emacs (>= 23.2)收到非常多的
    WM_IME_STARTCOMPOSITION消息，导致xkeymacs以为进入输入法状态。修改一下..dll.cpp里面
    InitKeyboardProc函数就好了 [2011-02-14 16:47:10]
75. [工具软件] 续: 具体修改方法是xkeymacsdll.cpp的InitKeyboardProc函数里，在SetApplicationName之前判
    断一下CUtils::IsEmacs，如果是就将bImeComposition设为真 [2011-02-14 16:56:35]
76. 修改倒是简单，安装Visual Studio折腾死我了，先安装了VC6企业版，同事说这个版本有问题，又装了VC6专
    业版（其间还为了企业版卸载不掉折腾了半天），发现win32api的.h和.lib太老编译不过，最后装了VS 2005
    才搞定 [2011-02-14 16:58:57]
77. [工具软件] 续: 顺便还改了一下对xemacs/uemacs的缺省禁用，一些console程序的判断，中文Windows上的一
    些窗口判断（原版是针对日文版判断的） [2011-02-14 17:01:28]
78. [firefox][addons] Brief 终于升级了（不过好像只有UI方面的变化?)  ID: 4578
    https://addons.mozilla.org/zh-CN/firefox/addon/brief/ [2011-02-14 20:13:32]
79. [vim][linux] Linux下gvim菜单文字均为空白的解决方法(原来只是因为utf-8和utf8中间一个字符的差别，囧)
    http://ekd123.is-programmer.com/posts/24423.html [2011-02-14 21:56:42]
80. [工具软件] notepad2-mod中文版 http://hi.baidu.com/zhfi1022 [2011-02-14 22:00:05]
81. [RIL][并发] C++ 多线程系统编程精要 - 陈硕的 Blog - 博客园
    http://www.cnblogs.com/Solstice/archive/2011/02/12/1952773.html [2011-02-14 22:17:57]
82. [firefox][vim] Pentadactyl搞什么名堂，明明vim里面就叫incsearch, hlsearch，它偏要改成incfind,
    hlfind，是故意跟vimperator保持不一致么? [2011-02-15 08:45:38]
83. [python] Building Python with the free MS C Toolkit
 http://wiki.python.org/moin/Building%20Python%20with%20the%20free%20MS%20C%20Toolkit [2011-02-15
 08:57:10]
84. [工具软件] everything一个很不爽的地方是不能配置快捷键来对文件做一些操作（比如跳到TC/FAR相应目
    录），而这是需要频繁使用的，相对而言locate32最开始配置数据库麻烦一点也不是什么问题了
    [2011-02-15 09:33:06]
85. [devtools] EA的界面做得实在不咋样，对话框上各个元素之间根本看不明白逻辑关系，还不如用dia——俺们公
    司为啥选EA，还真相信可以直接产生代码框架？(考虑到UML本身的复杂性) [2011-02-15 09:37:29]
86. (EA) 同样是Attributes和Operations，在class的属性里就有入口，在interface里面就死活找不到，找来找
    去发现在diagram界面的右键菜单里 [2011-02-15 13:16:36]
87. [工具软件] 还是改用dia来画部署图了。不过居然要将IME设置为Simple才能输入中文，设为Windows IME反而
    不行，奇怪。 [2011-02-15 17:37:24]
88. [emacs][python] RT @yunh: A new major-mode for Python
    http://lists.gnu.org/archive/html/emacs-devel/2011-02/msg00655.html [2011-02-16 00:16:09]
89. [emacs][iphone] RT @basimple: #Emacs for iPhone  http://gamma-level.com/iphoneos/ports/emacs
    [2011-02-16 00:17:35]
90. 咦，啥时候闪存可以中间加tag了，再试试: [foobar] ——blahblah [2011-02-16 17:28:37]
91. [FAR][addons] 这个MacroLib插件不错，可以不太常用但又挺必要的插件可以用宏来代替了
    http://code.google.com/p/far-plugins/wiki/MacroLib [2011-02-16 19:33:11]
92. [uemacs] 刚才无意中发现jasspa里面可用esc =激活主菜单（原来禁用了Alt+<key>激活菜单之后就一
    直困惑这个），esc +激活上下文菜单。但没找到关闭的方法 [2011-02-16 20:11:00]
93. PPT，找着你的图片。PPT，写着你的文件。PPT，想着你的观点。开完会，一切变大便；PPT，一周写满七天。
    PPT，夜夜做到零点。PPT，没有性生活时间。老板说：不满意重写！（ @和菜头 + @Raiven_s )
    [2011-02-17 08:54:55]
94. [emacs] RT @xah_lee: RT @johnnyjacob: Very good #emacs #elisp tutorial - http://is.gd/k3szbw
    [2011-02-17 09:07:12]
95. [unix][RIL] Nine traits of the veteran Unix admin http://bit.ly/hVfNyv [2011-02-17 09:07:36]
96. 奇怪，为了换一个看着不那么费眼的主题，我用gtk-win替代了dia自带的gtk，但SVG格式却加载不上了
    (librsvg也装了）。另: gdk-pixbuf-query-loader现在只有librsvg这一个结果了，难道是因为
    gdk->cairo引起的？ [2011-02-17 09:58:24]
97. [firefox][addons]Color Toggle: Toggles the fg/bg/link colors between 2 values (id:9408)
    https://addons.mozilla.org/en-US/firefox/addon/9408 [2011-02-17 11:28:10]
98. [km][RIL] RT @young_yang: Twitter 的默认搜索只能够搜索到大概 7 天之内发表的信息，而如果要搜索更
    早之前发表的信息，就需要借助其他的搜索引擎。——《10 个可以搜索推特上旧信息的网站》:
    http://is.gd/EhtV0P [2011-02-17 15:12:44]
99. [emacs] 对外发了俺写的第一个emacs扩展: 用Scite API文件作为自动补全函数源
    http://bamanzi.is-programmer.com/posts/24558 [2011-02-17 23:51:04]
100. [TODO] blog: 介绍FAR（以及推荐插件) [2011-02-18 09:19:24]
101. [TODO] blog: cygwin vs mingw vs colinux [2011-02-18 09:19:41]
102. [TODO] 介绍microemacs，主要是jasspa [2011-02-18 09:20:08]
103. [TODO] blog: 发布FavMenu修改版 [2011-02-18 09:20:27]
104. [TODO] blog: 用org-mode写文档 （估计得分3－4篇来写） [2011-02-18 09:21:19]
105. [TODO] 在家装一个Visual Studio 2003+，把xkeymacs该完，将补丁发给原作者 [2011-02-18 09:22:48]
106. [工具软件] 折腾了许久的轻量级代码编辑器，scite,pspad,pn,scite-ru,akelpad, 最终还是notepad++，算
     了，抛弃掉对它的成见，从了吧 [2011-02-18 11:07:22]
107. [emacs] 从 http://alpha.gnu.org/gnu/emacs/windows/ 下载新的v24 alpha版本，发现org更新到了7.3, 多
     了一些theme。 [2011-02-18 17:04:51]
108. [emacs] 续：刚发现我上次安装的是20101110, 再上次是20100708，不算太频繁哈。（之前都是从e4w项目下
     的 http://code.google.com/p/emacs-for-windows/ ) [2011-02-18 17:27:29]
109. [debian][RIL] Introducing the Debian packaging tutorial
     http://www.lucas-nussbaum.net/blog/?p=640 [2011-02-18 17:53:08]
110. [delphi] RT @andremussche: Cool: #Delphi Prism for #Java!  (and #Android) Codename #Cooper (see
     end of blog) http://lnkd.in/Nu4PXe [2011-02-19 08:14:59]
111. [vim][linux] gnome-terminal里面退出vim后造成终端乱码，简单解决办法：删除vim-gnome包 [2011-02-19
     18:51:10]
112. [gfw] ssh -qTfnN -D localport sshserver:port [2011-02-19 20:21:57]
113. [uemacs][blog] 新文章: 介绍一下MicroEmacs http://bamanzi.is-programmer.com/posts/24605
     [2011-02-20 20:35:26]
114. [工具软件] 轻量级.eml文件查看器 http://www.mitec.cz/mailview.html [2011-02-20 22:00:46]
115. [firefox][addons] Tile Tabs (id: 71411) - Allows tabs to be tiled within firefox. Tiles can be
     arranged horiz/vert or in a grid. [2011-02-20 22:25:16]
116. [scite] scite4chinese 基于scite-ru，从它那里取了一些功能过来
     http://code.google.com/p/scite4chinese/ [2011-02-20 22:33:14]
117. 微博小秘书提醒大家不要讨论不宜话题，想起一个台湾老段子：酒吧内，甲：唉。乙：唉。丙：唉。丁：不许
     谈国事。(胡淑芬) [2011-02-20 22:43:26]
118. [gfw] 今天它真是火力全开啊，好多网站都上不了，我想再访问一下 jasspa.com 都不行 [2011-02-20
     23:17:39]
119. [firefox][addons] Redirector (id: 5064) [2011-02-21 13:19:36]
120. [linux] 哈哈，我在淘宝上买的debian 6, mint 10, opensuse 11.3 DVD到了 [2011-02-21 16:44:56]
121. [firefox] 在办公电脑上将Pale Moon切为了主浏览器，Firefox 4为副，后者主要用于个人兴趣
     （Debian/Python/Emacs等）。原来是fx3.6+pm3.6，之所以需要一个pm，是两个fx会打架，而pm和fx之间不会
     [2011-02-21 16:47:15]
122. [firefox] 这次决定让我上fx4的主要原因是Panorama (原来叫做Tab Candy)。想在fx3.6上找一个类似的，没
     找到，那个TabGroup Manager的设置界面太繁琐了，主观上排斥 :-( [2011-02-21 16:49:26]
123. 急聘 兼职网络信息回复员（若干名）100元/天 工资日结 http://www.qianji.info/%3F56936.htm
     [2011-02-22 11:23:29]
124. [vim][geek] Vim Emulator Plugin for Visual Studio http://github.com/jaredpar/VsVim [2011-02-22
     13:23:51]
125. [totalcmd][scite][addons] SciLister能配合的最后一个版本是scite 1.74。另外scilister在遇到比较长的
     行时会导致高额CPU占用 [2011-02-22 14:29:52]
126. [totalcmd][addons] 删除highlighter.cnf后GSALister能快一些，而且不影响其功能（内置了一份配置）
     [2011-02-22 14:32:11]
127. [firefox][addons] Memory Fox: addtempting to reduce the browser's RAM memory usage
     (id:53880) 兼容fx4 [2011-02-22 14:50:04]
128. [firefox][addons] faviconizetab (id: 3780) http://addons.mozilla.org/firefox/addons/3780/ 装上后
     在vimperator中可用:js faviconize.toggle()来切换 [2011-02-22 15:27:12]
129. 我在当当买的《程序员》09、10精华本下午到了，怎么10年的比09年的薄很多，电子版光盘也没有
     [2011-02-22 21:02:45]
130. 汪峰的新专辑《信仰在空中飘扬》算是听完了我第一遍，总体感觉不如以前的，就那首《春天里》似乎还真不
     如旭日阳刚唱的 [2011-02-22 21:07:42]
131. [debian] win32-loader - Debian-Installer loader for win32
     http://packages.debian.org/squeeze/win32-loader [2011-02-23 08:45:44]
132. [debian][colinux] 哈，用淘宝上买的Debian 6 DVD升级了俺colinux里面的lenny，只有十来个包需要从网络
     下载，总共不到20分钟升级就完成了 [2011-02-23 09:16:15]
133. 刚发现vrome 也有上一页、下一页功能了(用[[和]]) [2011-02-23 10:18:58]
134. [firefox][addons] Status 4 Ever http://www.ru.kernel.org/mozilla/addons/235283/ [2011-02-23
     11:25:44]
135. [工具软件] Arsclip 优点是支持RichText（其它几个均不支持RichText），有合并粘贴功能，缺点是用大量
     文件做cache，而且不太稳定，常常导致剪贴板被锁 [2011-02-23 13:19:49]
136. [emacs] emacswiki RIL: ScimBridge_Chinese, AutoPairs, DumpEmacs [2011-02-23 16:25:03]
137. 据/.报道，一位博客作者统计了github的commit信息中出现七个脏字的频率，结果发现C++，Javascript和
     Ruby程序员爆粗口的次数最多，而最喜欢装的是PHP程序员。使用最多的脏词是shit
     http://solidot.org/article.pl?sid=11/ [2011-02-23 22:47:44]
138. Solidot | 统计表明C++程序员最爱爆粗口 http://solidot.org/article.pl?sid=11/02/23/0323207
     [2011-02-23 22:48:51]
139. The only valid measurement of code quality: WTFs/minute
     http://manasg.com/wp-content/uploads/2010/07/codereview-300x271.jpg [2011-02-23 22:52:46]
140. [TODO] GR subscribe http://www.cnblogs.com/lidaobing/ [2011-02-24 07:32:46]
141. [linux][工具软件] 现在找stardict 词典比较困难了，这里有一些 http://code.google.com/p/dict/
     [2011-02-24 08:44:59]
142. [linux][totalcmd][far] 打算以后旧硬盘备份不用ghost做镜像了，改用squashfs 格式，可以用
     7-zip/TC/FAR 打开，还可以在colinux里面mount 上去再用浏览器/ftp方式 浏览，哈 [2011-02-24
     10:55:22]
143. [工具软件] arsclip 的一个好处是有长名单和短名单之分，可以记录非常多的历史，而菜单上只显示最后xx
     个。clcl和clipx都只有一个配置项，要么菜单太长，要么想找旧数据而不可得 [2011-02-24 13:23:46]
144. [firefox] 我太善变了，fx4耗内存太多，我又回到fx3.6的怀抱。啥时候fx才支持多进程方式啊，我觉得这才
     是fx最需要向chrome学习的东西，UI方面就不要折腾太多了 [2011-02-24 13:28:33]
145. [工具软件] 跟FavMenu类似的工具有: FolderMenu, FlashFolder, DirectFolders (前两个是开源工具，都在
     sf.net上) [2011-02-24 17:41:09]
146. [uemacs] jasspa最大的缺点是不支持各种encoding （至少得支持utf-8, utf16-le & 当前ANSI吧）
     [2011-02-24 17:50:59]
147. [emacs][php][openproxy] 查PHP函数可以用这个网址
     http://php.chinaunix.net/manual/zh/function.{function}.php 不过function里面要将_变成-
     [2011-02-24 18:11:04]
148. [iphone] 在网上看了一个星期的相关文章，打算升级到iOS 4.0.1了，这是能用jailbreakme越狱的最后一个
     版本。现在很多网站被封，其它的越狱方法大都不能用了。而且4.1和4.2也没有什么太吸引我的特性
     [2011-02-25 09:38:30]
149. git 下载最新代码（而不clone: git archive -v --format=tar
     --remote=git://wine.git.sourceforge.net/gitroot/wine/wine-gecko HEAD > win-gecko.tar
     [2011-02-25 13:33:52]
150. [openproxy][cygwin] http://www.gi.kernel.org/sites/sourceware.cygnus.com/pub/cygwin/
     [2011-02-26 15:41:03]
151. [openproxy][cygwin] http://www.ru.kernel.org/mirrors/ftp.cygwin.com/ [2011-02-26 15:41:32]
152. [openproxy][cygwin] http://www.alpaca-farm.lkams.kernel.org/pub/cygwin/ [2011-02-26 15:42:49]
153. [debian][mint] 把Debian Testing变成LMDE http://www.linuxsir.org/bbs/showthread.php?t=374950
     [2011-02-26 15:44:36]
154. [emacs][RIL] Sylvester324 :在Emacs中构建我的字典（sydict） 使用startdict的文件创建我自己的Emacs
     字典查询函数。http://sinaurl.cn/hGSuSA [2011-02-28 07:26:48]
155. [emacs][RIL] Making Emacs Stand Up To Visual Studio 7 || kuro5hin.org
     http://www.kuro5hin.org/story/2003/4/1/21741/10470 [2011-02-28 07:39:18]
156. [vim][RIL] http://hotoo.googlecode.com/svn-history/r297/vimwiki/Vim.html [2011-02-28 07:53:43]
157. [emacs][encoding] 高宇翔如是说 :[Tips] Emacs字符编码相关指令 http://sinaurl.cn/hGtm3A
     [2011-02-28 08:08:08]
158. [emacs][RIL] RT @edipretoro: Emacs-fu: executable source code blocks with org-babel:
     http://tinyurl.com/4lt9jnb (#orgmode #emacs) // great t [2011-02-28 08:21:19]
159. [emacs][RIL] RT @xah_lee: A Text Editor Feature: Extend Selection by Semantic Unit
     http://goo.gl/LdDbZ #Mathematica #emacs #vim #eclipse [2011-02-28 08:35:05]
160. [TODO]https://bamanzi.sugarsync.com/getfiles/c3oaftnh8f9j0 [2011-02-28 09:45:57]
161. [emacs] 刚意识到之所以我会在闪存上加了许多Xah Lee的文章到RIL标签上，是因为Xah Lee不在Planet
     Emacsen上(为啥?)，于是到GR上订阅了他的RSS，这里就不轻省了，哈 [2011-02-28 10:37:47]
162. [debian] apt限速: $ apt-get -o Acquire::http::Dl-Limit=20 -o Acquire::https::Dl-Limit=20
     upgrade -y 来自commandlinefu [2011-02-28 10:43:22]
163. [firefox][addons] Javascript Debugger (id:216)
     http://www.df.lkams.kernel.org/pub/mozilla/addons/216/ [2011-02-28 13:14:20]
164. [firefox][addons][web][devtools] Firebug (id:1843)
     http://www.df.lkams.kernel.org/pub/mozilla/addons/1843/ [2011-02-28 13:16:36]
165. [firefox][addons] Execute JS (id:1729) http://www.df.lkams.kernel.org/pub/mozilla/addons/1729/
     [2011-02-28 15:54:17]
166. [TODO] beyond compare [2011-02-28 17:24:46]
167. [TODO] GR subscribe http://hi.baidu.com/lotabout/blog/category/Emacs/ [2011-02-28 20:48:15]


