
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2011-11
  :PROPERTIES:
  :PAGE:     ing/2011-11.html
  :ARCHIVE_TIME: 2014-01-11 六 14:20
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. [emacs][Tip] Fixing the mark commands in transient mark mode
   http://www.masteringemacs.org/articles/2010/12/22/fixing-mark-commands-transient-mark-mode/
   [2011-11-01 09:11:28]
2. [emacs][javascript][tip] Beautify your JavaScript in Emacs
   http://sethmason.com/2011/04/28/jsbeautify-in-emacs.html [2011-11-01 09:12:16]
3. You Will Be Able To Run Soon Android Apps On Your iPad With This App !
   http://www.ultrasn0w.ca/2011/10/run-android-apps-on-your-ipad-with-this.html [2011-11-01
   09:14:31]
4. Install Linux Applications Without Root Privileges With Zero Install
   http://www.addictivetips.com/ubuntu-linux-tips/install-linux-applications-without-root-privileges-with-zero-install/comment-page-1
   [2011-11-01 09:16:49]
5. [firefox][tip] Stop Firefox from Greying Out URLs in the Navigation Bar
   http://lifehacker.com/5847846/stop-firefox-from-greying-out-urls-in-the-navigation-bar
   [2011-11-01 09:19:18]
6. [工具软件] Text Editor Anywhere is a small tool that allows you to edit text anywhere with your
   favorite text editor.  http://www.portablefreeware.com/?id=2188&ts=1319978701 [2011-11-01
   09:56:21]
7. 这次Google Reader改版，无法访问g+的大陆网友不满意（比如月光博客），能访问g+的台湾网友也不满意（比
   如電腦玩物） [2011-11-01 14:30:05]
8. [evernote][firefox] Evernote Web Clipper更新了，新特性是: Article clipping enabled for 'Send to
   desktop' 不过firefox扩展5.0.0.201551版本还"没经过mozilla审核"，需要到"see complete version
   history"里面去安装 [2011-11-01 17:26:12]
9. [ipython] ”The Qt frontend has hand-coded emacs-style bindings for text navigation. This is not
   yet configurable. ” :-) http://ipython.org/ipython-doc/dev/interactive/qtconsole.html
   [2011-11-02 11:04:59]
10. 由美国大学毕业生布雷特&#183;凯勒(Brett Keller)发起的请愿活动，迄今已有一万多用户在请愿书上签字，
    希望Google能换回以前的Google Reader版本。http://www.williamlong.info/archives/2872.html
    [2011-11-02 14:30:03]
11. “如果我问我的用户，他们只会说要一匹更快的马。”—亨利•福特（Henry•Ford，1863—1947），美国汽车工程
    师与企业家，福特汽车公司的建立者。 [2011-11-03 09:30:52]
12. [工具软件] 把metapath做为scite或者universal viewer的目录浏览器倒是个不错的主意（各自拷贝一份，然
    后使用不同的Target配置) http://www.flos-freeware.ch/archive.html [2011-11-04 09:55:37]
13. [工具软件] 对比了一下代码才想起当初我对metapath的代码做hack是改了什么: 添加了一个-t target.exe的
    支持，使得可以从scite/uviewer动态设置target程序 [2011-11-04 09:57:58]
14. [firefox] 认真评估了一下selected search, 比Universal Search /IE8 Accelater稳定。但自动弹出比较烦
    人，不能配置为按住Ctrl时选择文字弹出。从这一点上说，不如还是用Context Search (RG) [2011-11-04
    15:03:14]
15. 我机器上的epy已经被我改得面目全非了，目前是这样几个模块:
    epy(autoloads,defgroup)/epy-setup(PYTHONPATH,PATH)/epy-menu/epy-ropemacs/epy-checker/epy-misc, 原
    来epy里面一些不太相关的个性化设置都被我挪到epy-custom了 [2011-11-04 18:06:01]
16. 偶也，通过ifttt将google reader上加了特殊标记的文章共享到twitter，试验成功（有两种，一种带图，一种
    不带） [2011-11-06 12:24:11]
17. 原来geany-plugins已有预编译的windows包 http://plugins.geany.org/geany-plugins/ [2011-11-07
    09:12:11]
18. [python] 我正打算开始动手，发现一个比较接近我想法的东西：PySlices
    http://code.google.com/p/wxpysuite/ 是pycrust的改进版，支持多行编辑(然后Ctrl-Enter执行)，另外从
    ipython借了几个交互方面的改进点过来 [2011-11-07 10:18:03]
19. 不对呀，这个pyslices早已经wxpython-wxtools里面存在，查了一下ChangeLog，发现14-May-2010的2.8.11.0
    已经有了这些功能了，对比代码觉得差异很小，除了多了个SymPySlices [2011-11-07 10:23:16]
20. [javascript] 本来是去说隔了好几年，去看一下wxjs有什么新版本，结果发现了gluescript, 然后转到gpsee
    网址，然后又转去CommonJS网站（这个好像被墙了）。同时发现SpiderMonkey这个生态圈也挺红火，比nodejs
    差不了太多啊 [2011-11-07 17:33:09]
21. [javascript] 现在JavaScript到处都在用啊 Comparison of open source configuration management
    software: http://is.gd/9D7xk3 CommonJS: http://is.gd/bCSsj6 [2011-11-07 17:46:14]
22. linuxmint上安装ubuntu one: apt-get install ubuntuone-client-gnome && apt-get install
    ubuntuone-control-panel [2011-11-08 09:27:10]
23. Popularity contest statistics for emacs,vim (via qa.debian.org) http://is.gd/TUC2UH [2011-11-08
    10:38:13]
24. 发现gluescript最大的问题是：一点文档没有，都不知道每个模块有哪些API可调 [2011-11-08 12:38:08]
25. 有两个同名同用途的项目还真是挺烦: eproject: 1)http://www.emacswiki.org/emacs/eproject
    2)https://github.com/jrockway/eproject [2011-11-08 20:12:15]
26. TabGroupManager和BarTab这两个扩展真是爽，Firefox上对付开太多页面的神器啊，我现在"开着"49个页面，
    内存占用77M，虚拟内存195M [2011-11-09 11:20:50]
27. [emacs] 终于，终于找到了在emacs-lisp-mode下禁止CEDET(sf.net版本)的imenu索引函数的方法了, 原来
    cedet引入了一种mode-local变量。所以需要(setq-mode-local emacs-lisp-mode
    imenu-create-index-function 'imenu-default-create-index-function) 而旧式setq是不行的 [2011-11-10
    15:18:40]
28. [emacs] 而GNU Emacs内置的CEDET则默认没在emacs-lisp-mode上启用semantic-mode (见
    semantic-new-buffer-setup-functions)。想在sf.net版本上找类似的功能(对某种它支持的文件类型禁用)，
    但没找到 :-( [2011-11-10 15:21:25]
29. [emacs] nuke-some-buffer http://www-cdf.fnal.gov/~sthrlnd/emacs_help.html [2011-11-10 15:51:36]
30. ”微软在今年3月份火狐4发布时向 Mozilla 赠送了一个大蛋糕表示祝贺，但是随着火狐版本更新速度的加快，
    微软赠送的蛋糕也越来越小，直到火狐8不再赠送。” http://news.cnblogs.com/n/121278/ [2011-11-11
    09:18:05]
31. [firefox] BarTab有firefox 4+的版本了 https://github.com/fhoech/BarTab 不过目前得自己做一下xpi包。
    相比BarTab Lite的有点是这个不仅可以启动时不加载未访问的标签页的内容，还可以运行中unload
    [2011-11-11 13:24:34]
32. [g_f_w] 目田冂 7.21 你懂的 http://files.cnblogs.com/bamanzi/f721.rar [2011-11-14 08:44:49]
33. 用户们开始在gnome-list上讨伐GNOME 3了，好多跟贴
    http://mail.gnome.org/archives/gnome-list/2011-November/msg00002.html [2011-11-14 08:49:44]
34. 最近见到的吐槽文特别多啊: Why I think MySQL is a toy
    http://grep.be/blog/en/computer/cluebat/mysql_toy_argument [2011-11-14 13:55:13]
35. 将代码文件与其svn base进行比较: C:\Program Files\TortoiseSVN\bin\TortoiseProc.exe /command:diff
    /path:%P%N 在TC里配个快捷键，比每次点好几级菜单方便多了 [2011-11-14 17:42:55]
36. EmacsWiki上新出现了一个windcycle模块 http://is.gd/EkQM41 正是我感兴趣的 window swapping &
    cycling，本来想用来替换掉我自己写的实现，但看了一下代码，觉得还不如我写的 :-) [2011-11-15
    09:15:40]
37. [firefox] Split Panel工具栏上关闭按钮的图标显示异常（显示很多个图标，但只对应关闭功能）的问题，突
    然间就好了。看了一下它自己并没有更新，这两天自动更新的只有pano和googledictionary两个扩展，估计是扩
    展冲突导致的了 [2011-11-15 09:17:49]
38. [emacs] 也许tempo-snippets是我想要的多热点的代码模板扩展
    http://nschum.de/src/emacs/tempo-snippets/ （我觉得yasnippets的模板配置占用太多小文件了，有点抵触。
    而且tempo本身已经收录到GNU Emacs [2011-11-15 11:56:36]
39. [emacs] 多窗口配置方面又发现了两个新东西 el-screen (不是elscreen)
    https://github.com/medikoo/el-screen 和 windows-mode http://www.emacswiki.org/emacs/WindowsMode 不
    过我发现我的需求目前用自带的register可以搞定 [2011-11-15 15:08:23]
40. [FAR] 折腾了半天，才搞定用F3激活colorer来查看文件，方法是在FAR Macro Browser插件里面新建一个
    宏，Command为F3, 而Sequence为c l r : CtrlEnter Enter(注意空格) [2011-11-16 17:21:12]
41. [FAR] 续: 另外，似乎得关闭colorer的TrueMod color支持，它跟conemu的配合不是太好（即使打开了conemu的
    truemod开关） [2011-11-16 17:26:59]
42. [autohotkey] 这个网站有好多不错的小工具，基本上都是用autohotkey写的，带源代码，我打算集成几个到我
    自用的FavMenu里面去。 http://www.donationcoder.com/Software/Skrommel/ [2011-11-17 09:14:43]
43. [工具软件][autohotkey] 续: 以前见过的一个给任意程序添加工具栏的Barnacle也是出自这里，不过下载下来
    不能用，源代码也得改改才能在新的AHK下跑
    http://www.donationcoder.com/Software/Skrommel/index.html#Barnacle [2011-11-17 09:16:13]
44. [unix][shell][terminal] multitail - view multiple logfiles windowed on
    console #color #ncurses #console http://packages.debian.org/wheezy/multitail [2011-11-18
    08:49:57]
45. [unix] Ted, a Rich Text Word Processor - LG #44 #rtf #xwindow #apps
    http://linuxgazette.net/issue44/ayers.html [2011-11-18 08:59:28]
46. #unix 下一些练习打字(英文)的软件 #typist #keyboard http://www.gnu.org/software/gtypist/#others
    [2011-11-18 09:07:24]
47. [unix] stunnel is a program that allows you to encrypt arbitrary TCP connections inside #SSL
    . it can allow you to secure non-SSL aware daemons and protocols (like POP, IMAP, LDAP, etc)
    http://www.stunnel.org/ [2011-11-18 09:10:27]
48. Windows DLL不能使用主程序或者早先加载的DLL里面的符号（即可在运行期解析到）？这里有一个解决方法:
    FlexDLL http://alain.frisch.fr/flexdll.html 对移植程序应该有帮助 [2011-11-18 09:19:06]
49. 『每一个做软件的人看完这本书都会发出“软件难做“的感慨。』-《梦断代码》读后感 - really's Blog
    http://fff5706.is-programmer.com/posts/30824.html [2011-11-18 13:27:00]
50. 『在软件开发的过程中，最难的就是精确设定要做什么东西，osaf的那群牛人们很无奈的在到底要把chandler
    做成什么样这个问题上纠结了许久。软件架构改了又改。一会儿要p2p实现，一会儿又只能接受搭建一个服务器
    用webDAV实现；一会儿要做桌面应用，一会儿又纠结是不是用mozilla的界面组建做一个浏览器插件更方便些。』
    [2011-11-18 13:32:23]
51. 『只能说，软件最初的目标太过伟大了。不仅仅要实现数据的灵活处理，还需要软件的组件能够向乐高积木一
    样重用。于是，osaf的程序员们只能不断的去寻找可以直接利用的代码，又因为拿到的代码不能完成软件的
    “杀手级功能“而放弃，然后纠结是继续找新的模块还是自己从头开始写。』 [2011-11-18 13:32:34]
52. 『软件时间黑洞的概念在这里诠释的淋漓尽致。而且，随着黑洞的持续，程序员们为了打破黑洞的死循环，不
    断的改需求以确保能够做出真正能用的软件。而需求的不断变化正是现代软件工程中最忌讳的事情。』
    [2011-11-18 13:32:51]
53. [javascript][json][python] pretty-print json with python: $ cat foobar.json | python -mjson.tool
    [2011-11-18 14:24:10]
54. Barnacle修正: #228改为 Gui,1:Show,w200 h200,Barnacle #283改为Gui,2:Add,Picture,%image_2%,
    %image_1% [2011-11-18 18:15:15]
55. Mount #ISO & IMG files With Furius #Mount [Linux] -
    http://www.makeuseof.com/tag/mount-iso-img-files-furius-mount-linux/ [2011-11-19 10:45:57]
56. [firefox] 以为Firefox 4把Remote XUL完全删除了，原来只是默认不支持了，还有一个白名单 Remote XUL
    Manager - https://addons.mozilla.org/zh-CN/firefox/addon/remote-xul-manager/?src=search
    [2011-11-19 20:19:40]
57. [firefox] TabGroups Manager支持Firefox 4+的内置分组(panorama)了，不过现在把标签栏跟TGM工具栏绑定
    在一起了，用不了Tabs on top这个特性了 [2011-11-19 20:20:57]
58. [工具软件] 多桌面软件dexpot有1.6beta版了，新特性有：支持多显示器，应用程序绑定桌面，所有程序固定
    在任务栏(win7)，屏幕四角热点，多配置文件 http://www.dexpot.de/index.php?id=beta16 [2011-11-21
    09:47:02]
59. [firefox][keysnail][TODO] 将Mar Mod提供的in-place翻译功能移植到keysnail上，这样我在Firefox 3.x上
    也可以使用了，而且可以通过快捷键触发 [2011-11-21 10:50:37]
60. Legend of the Condor Heroes - 射雕英雄传 Return of the Condor Heroes - 神雕侠侣 :-) [2011-11-21
    12:59:14]
61. 上周买了湖南岳阳的绿茶，20多元半斤装，喝了几天觉得还不错。我觉着这个价位比较适合我，不喜欢那些暴
    贵的龙井、铁观音神马的 [2011-11-21 16:53:53]
62. [cygwin] 终于mintty变为默认安装的了，并且会在开始菜单里建立快捷方式Cygwin Terminal 『Updates:
    setup.exe (Release 2.761)』 - http://cygwin.com/ml/cygwin-announce/2011-11/msg00043.html
    [2011-11-22 08:51:54]
63. [cygwin] cygwin的setup.exe有个问题: 如果你想加装一个软件，它会根据最新的setup.ini把其它已经有新版
    本的软件包也给升级了。这种情况下还是用cyg-apt比较方便——不过cyg-apt只会安装那些尚未安装的依赖包，
    而不会自动升级，究其原因，是cygwin setup.ini里面的依赖关系只有包名，没有象debian/redhat那种将版本
    号也放在依赖里 [2011-11-22 08:52:12]
64. [devops][todo] InfoQ: 百度技术沙龙第19期回顾：DevOps，全功能交付团队（含资料下载） -
    http://www.infoq.com/cn/news/2011/10/baidu-salon-19th-summary [2011-11-22 11:55:11]
65. 在Debian News看见一个基于gtk2的编辑器x2 http://packages.debian.org/wheezy/x2 只有110K的体积居然还
    有syntax highlighting，想见识一下，在Debian 6上却运行不了，因为它需要gtk-2.24的GtkComboBoxText，
    但目前只有2.20，回头在Ubuntu natty上试一下吧 [2011-11-22 18:08:29]
66. 中国移动MM的广告太矬了 [2011-11-23 08:30:31]
67. [emacs] (用auto-insert-mode实现)Emacs中新建文件使用模版 http://www.shahuwang.com/?p=36
    [2011-11-23 08:57:46]
68. [far] 在Fanfare iTest讲述与Rational Quality Manager集成的视频中看到这个家伙在使用Far manager :-)
    http://wiki.fanfaresoftware.com/display/vid1/Rational+Quality+Manager+Integration [2011-11-24
    17:02:28]
69. [far] 又看到一个不错的插件Screen Gadgets，可以给FAR的界面上添加一些"按钮"——不过问题是，如果你会配
    这些按钮，你也就知道怎么访问那些功能，也就用不着按钮了，除非你是给别人配置的
    http://code.google.com/p/y-projects/ [2011-11-25 09:13:44]
70. [unix] Save man-page as pdf: man -t awk | ps2pdf - awk.pdf
    http://www.commandlinefu.com/commands/view/9751/save-man-page-as-pdf [2011-11-25 09:32:26]
71. [emacs][python] pdee: Python Development Emacs Environment 基于emacs-for-python
    https://github.com/pdee/pdee [2011-11-25 09:56:01]
72. [unix] archivemount可以让你直接加载一个压缩包(tar,tgz,cpio,tar.bz2)到fuse，可读可写，跟winmount比
    较象 http://www.ibm.com/developerworks/aix/library/au-spunix_newfs/index.html#any_archive
    [2011-11-25 10:12:51]
73. [unix][fuse] 这里有更多内容: ArchiveFileSystems - fuse
    http://sourceforge.net/apps/mediawiki/fuse/index.php?title=ArchiveFileSystems [2011-11-25
    10:13:44]
74. [emacs][todo] dave-indent.el需要添加对indent-tabs-mode的支持, 尤其dave-unindent函数在回删的时候计
    算要删的字符数不能再用point数来算了，要按column来算 [2011-11-25 16:20:28]
75. [emacs][todo] dave-indent.el 另外再添加一个dave-indent-mode吧，方便临时启用 [2011-11-25
    16:56:03]
76. [emacs][orgmode] 这个技巧不错，用得上: 『在emacs上使用博客园的代码功能』
    http://www.cnblogs.com/Open_Source/archive/2011/11/27/2264756.html [2011-11-28 10:04:06]
77. Perl 6被吐槽了: "Parrot's was the best because it was vaporware. Ha! Ha, ha ha. "
    http://steve-yegge.blogspot.com/2008/06/rhinos-and-tigers.html [2011-11-28 13:35:41]
78. [工具软件] Minimize Windows as Thumbnails on Desktop Instead of Taskbar using miniMIZE -
    http://is.gd/U24XAT [2011-11-29 08:49:19]
79. Windows explorer tips: You can Press "ALT" Key While Drag-n-Drop a File or Folder to Create
    Shortcut? http://is.gd/fG65jg [2011-11-29 09:25:36]
80. Windows explorer tips: Press "CTRL" key and double-click on a folder or drive and it'll open it
    in a new window. http://is.gd/fG65jg [2011-11-29 09:26:54]
81. Windows explorer tips: You can Press "SHIFT" key and Click on "No" Button to Enable "No to All"
    Choice. http://is.gd/fG65jg [2011-11-29 09:27:39]
82. [emacs] 这个CopyFromAbove小技巧相当实用: 可快速复制上一行（或者逐个字符复制上一行中的一部分）
    http://www.emacswiki.org/emacs-en/CopyFromAbove [2011-11-30 10:06:15]
83. [工具软件] Path Editor: http://www.redfernplace.com/software-projects/patheditor/ [2011-11-30
    10:42:47]


