
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2012-05
  :PROPERTIES:
  :PAGE:     ing/2012-05.html
  :ARCHIVE_TIME: 2014-01-11 六 14:18
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. [firefox] Scrapbook Plus的介绍里作者说他正在开发2.0版本，需要邮件联系他获取beta版本，但没有透露
   任何细节 https://addons.mozilla.org/zh-CN/firefox/addon/scrapbook-plus/ [2012-05-02 21:33:36]
2. [emacs] : 将[orgmode]转换（导出）成[markdown]的方法:
   https://github.com/alexhenning/ORGMODE-Markdown [2012-05-02 22:32:46]
3. [vim]里面的modeline名词跟[emacs[里面的modeline完全不一样，emacs里面叫做file variables，示例:
   ;; -*- mode: Lisp; fill-column: 75; comment-column: 50; -*- [2012-05-03 12:08:22]
4. 除了-*- ... -*- 这种形式，[emacs]里还有多行的形式来指定file variable http://is.gd/wqeSQC
   (Emacs Manual: Specifying File Variables) [2012-05-03 12:14:04]
5. [emacs] 如果你的代码注释里有特殊的排版（比如列表、序号或者javadoc/doxygen方式的标记），Emacs自
   带的M-q是不够用的，可以试试filladapt.el提供的filladapt-mode
   http://www.emacswiki.org/emacs/FillAdapt [2012-05-03 15:42:14]
6. [emacs] 也自带adaptive filling功能(是个选项adaptive-fill-mode，缺省已打开 http://is.gd/4YOxtq
   )，但只会将-#*+这些符号作为fill prefix的一部分，原来的换行会被搞乱 [2012-05-03 15:57:38]
7. [emacs] doxymacs.el 里面有跟filladapt.el 相配合的配置 [2012-05-03 15:58:59]
8. win32 native port of 支持颜色的grep (grep --color)
   http://sourceforge.net/projects/ezwinports/files/ [2012-05-03 17:16:46]
9. 在cygwin-announce邮件列表里看见emacs-24-beta进入cygwin了，当前版本是24.0.96
   http://permalink.gmane.org/gmane.os.cygwin.announce/4068 [2012-05-07 09:55:02]
10. [firefox] 因需要在四种proxy配置间切换，toggle proxy只支持两种，而proxy selector又不支持fx3.6，
    找了个FoxyProxy Basic
    https://addons.mozilla.org/zh-CN/firefox/addon/foxyproxy-basic/?src=dp-dl-othersby [2012-05-07
    09:58:43]
11. [emacs] powerline.el 老导致各种各样的问题，不用了——虽说花哨好看 [2012-05-07 11:22:13]
12. [firefox] 在Edit Bookmark Plus的评论中有人提到这是个OpenBook的替代品，我找到OpenBook装上，发现
    它比E.B.P要好，因为还能修改“描述”字段。不过安装前需要自己修改一下install.rdf 里面的兼容版本限
    定 https://addons.mozilla.org/en-US/firefox/addon/openbook/?src=ss [2012-05-07 16:43:20]
13. Readability ：好阅读，难同步 - 爱范儿 &#183; Beats of Bits http://www.ifanr.com/77933
    [2012-05-07 17:59:12]
14. 靠，evernote.com都被强了 [2012-05-07 21:18:03]
15. Emacs 24 supports Subversion 1.7, but Emacs 23 does not. If you want to use Subversion 1.7 on
    Emacs 23, you can use vc-svn17.el for this purpose. https://github.com/buzztaiki/vc-svn17-el/
    [2012-05-10 09:50:30]
16. [emacs][svn] Fortunately, dsvn.el doesn't depend on .svn directories, and so it handled
    the new layout (of svn-1.7) just
    fine. http://gxc.google.com/gwt/x?u=http://benjisimon.blogspot.de/2011/10/gotcha-of-day-emacs-svn-support-breaks.html
    [2012-05-10 09:54:04]
17. Apache Subversion command line tools (for windows) http://www.visualsvn.com/downloads/
    [2012-05-10 10:25:05]
18. 干掉浏览器里烦人的走马灯 Disable the Marquee Tag http://www.felgall.com/marquee.htm (搞不定用
    JS写的那种) [2012-05-10 10:28:49]
19. windows下试图在emacs里搞定rgrep/lgrep功能是个异常麻烦的事情，因为find和grep的配合问题（主要问题
    还是windows的shell能力太差）。之前我用ack来规避，不过今天发现有个w32-grep.el 可以搞定这个（改用
    grep -r而不用理烦人的find了) http://emacswiki.org/emacs/NTEmacsWithCygwin#toc3 [2012-05-10
    19:26:07]
20. View in Readability http://www.readability.com/read?url=%URL% ; View in GWT:
    http://gxc.google.com/gwt/x?u=%URL% [2012-05-10 19:46:48]
21. Swiss File Knife - A Command Line Tools Collection, combines many functions in a single,
    portable executable that belongs onto every USB stick.  Search and convert text files, instant
    simple FTP/HTTP server, find duplicate files, compare folders, treesize, run own commands on
    all files of a folder - it's all within a single
    tool. http://stahlworks.com/dev/swiss-file-knife.html [2012-05-15 18:29:49]
22. 这个文件比较工具只依赖于python和gtk，可能更适合xfce里使用(meld依赖gnome, kdiff依赖kde, tkdiff和
    xdiff又太弱了) Diffuse - graphical tool for merging and comparing text files
    http://diffuse.sourceforge.net/ [2012-05-16 08:42:49]
23. TagsView - user interface for ctags parsed result. Supported editors: Notepad++, AkelPad. 比
    AkelPad自己的Coder插件强，后者的分析结果经常乱七八糟而且支持的编程语言也少。
    http://sourceforge.net/projects/tagsview [2012-05-16 08:45:54]
24. [unix][shell][perl] Look up a unicode character by name http://is.gd/gwTLyS [2012-05-16
    17:43:27]
25. 又看到一个类似github的项目: gitblit，全java打造，比gitlab的部署、升级容易多了，下周来试玩一下
    http://gitblit.com/setup.html [2012-05-18 17:47:40]
26. [shell] alias vless='/usr/share/vim/vim73/macros/less.sh' [2012-05-21 10:03:43]
27. "9) Design patterns are hurting good design more than they’re helping it." -- 十条不
    错的编程观点 http://kb.cnblogs.com/page/142347/ [2012-05-21 11:10:52]
28. 没想到这么多年之后，我那个老烘培机还在，我后来都没管过它，回头看看有没有什么内容值得下载下来保
    存一下的 http://www.woodfox.net/glyoung/ [2012-05-22 09:37:12]
29. 版本控制工具GitHub发布Windows版_cnBeta 软件新闻_cnBeta.COM
    http://www.cnbeta.com/articles/188367.htm [2012-05-22 10:01:43]
30. 前天用shuame.com那个一键解锁工具给我的火腿肠解锁之后，系统就时不时收到新应用的广告，开始以为是
    它那个刷机精灵搞的，卸载后之后还有，现在在看是不是Go桌面在搞鬼了——一个个排查吧，反正复位后我装
    的应用没几个 [2012-05-22 10:04:07]
31. 正在看shellex的博文《为什么我弃用Gnome转向KDE》(
    http://feedproxy.google.com/~r/shellex-cn/~3/6yVkefqmiBc/ )，想起他上次的文章里信誓旦旦地从vim
    转向sublime text，然后又灰溜溜地转回来。。。 [2012-05-22 11:09:49]
32. "努力加载评论中..." <a href="/u/1/" target="_blank">@dudu</a> 你们也太搞了
    [2012-05-22 16:40:36]
33. [emacs][python] 很奇怪，刚才调eepy的pycompletemine补全，输入(死活不会显示函数签名，调进去发现
    (thing-at-point 'python-dotexpr)返回nil，重新(load-library "thingatpt")后好使了，
    回头得查一下 [2012-05-22 22:23:45]
34. "Debian Wheezy 计划在6月下旬冻结" 好耶！—— 可是，我对GNOME 3没信心啊 [2012-05-23
    08:35:47]
35. 影帝有三宝：流泪、吟诗、到处跑。中国有三宝：人大，政协，党领导。历史有三宝：伟大，英明，查不到。
    领导有三宝：贪污，受贿，作报告。军警有三宝：抢尸，拆房，领导好。， [2012-05-23 14:13:13]
36. wxcommander原来说要在1.5添加的文件搜索功能，到现在都1.10了还是没有 [2012-05-23 15:02:05]
37. 东德笑话集（21则）－昂内克情人的礼物 http://article.yeeyan.org/view/129323/198869 [2012-05-23
    15:02:29]
38. 高级程序员装逼指南 (Zhuangbility Manual) - http://xahlee.org/lit/Zhuangbility_Manual.html
    [2012-05-23 22:15:47]
39. $ git remote add origin gitolite@hadoop-slave-15:foobar.git $ git push -u origin master
    [2012-05-24 10:17:17]
40. gconftool-2 --set /desktop/gnome/interface/gtk_key_theme Emacs --type string [2012-05-24
    13:17:09]
41. [xfce] xfconf-query -c xsettings -p /Gtk/KeyThemeName -s Emacs [2012-05-24 13:18:15]
42. RT @EnochLu: 哈哈,笑死.RT @ag108lau: 二战时期，主要负责搞笑的是意大利。（笑翻我了！）
    http://fun4hi.com/9068 [2012-05-24 13:20:40]
43. Read It Later变身Pocket之后，网站上的列表http://getpocket.com/unread 就没有搜索框了，想要搜索框
    得去新界面 http://getpocket.com/a/queue/ 但”老“浏览器无法打开这个页面，我的Firefox 9.0都被它
    鄙视了，让我升级，最后改了User-Agent串 [2012-05-24 14:38:58]
44. smartgit 这个客户端不错，比较“绿”，不会象msysgit/tortoisegit那样干扰其它软件的正常运行
    http://www.syntevo.com/smartgit [2012-05-24 16:49:55]
45. 看见python-mode.el发了新版本，就去下载下来试用，我靠，现在这家伙整这么多密密麻麻的菜单项，都不
    知道是些啥，补全也不能工作了——打开文档看看吧，好家伙，是每个命令的介绍，根本不是给人看的
    [2012-05-24 17:03:35]
46. 我上次用python-mode.el 还是6.0.2 [2012-05-24 17:03:59]
47. 【新词：自取其乳】词汇释义：改自传统成语“自取其辱”，反映当前人们对牛奶制品的恐慌，并呼吁人们
    尤其是哺乳期妇女用母乳喂养小孩。 [2012-05-25 09:38:21]
48. [firefox] 新版Tile Tabs可以配置成跟SplitBrowser比较接近的方式了：分屏不再是在单一标签页内，而是
    全局的，不过都是通过上面的标签栏来切换——要是隐藏标签栏，改用keysnail的C-x b来切换，就很有emacs
    的感觉 [2012-05-26 08:48:32]
49. [firefox] 续: Tile Tabs配置成全局分屏的方法是：在选项的“标签页”那一页，找到中部的“选中未分屏
    标签页时分配到激活分屏”, “选中已分屏标签页时分配到激活分屏”, “分屏关闭时分配另一标签页”三
    个选项，都勾上 [2012-05-26 08:49:55]
50. [shell] Piping to an emacs buffer with emacsclient
    http://mark.aufflick.com/blog/2011/03/03/piping-to-an-emacs-buffer-with-emacsclient
    [2012-05-26 16:12:45]
51. [emacs] elisp包的代码格式要求 ElispAreaConventions
    http://www.emacswiki.org/emacs-en/ElispAreaConventions [2012-05-27 21:27:09]
52. [emacs] 终于发现我的outline-org-headingmode有时不好使（标题行不再高亮）的原因（以及有时
    FIXME/TODO不高亮的原因)：跟develock冲突了，具体原因待查，暂时只能先禁用develock了 [2012-05-27
    22:23:28]
53. 常用python包一站式下载地址(限windows, 限python 2.6/2.7)
    http://www.lfd.uci.edu/~gohlke/pythonlibs [2012-05-28 13:42:53]
54. List all bash shortcuts: $ bind -P
    http://www.commandlinefu.com/commands/view/10804/list-all-bash-shortcuts [2012-05-29
    09:06:56]
55. 正在阅读: Expect 在网络管理中发挥着重要作用
    http://www.ibm.com/developerworks/cn/aix/library/au-expect/index.html [2012-05-29 12:13:36]
56. "This project (Unladen Swallow) had stated a goal of a five-times speed improvement over
    CPython. This goal was not met." http://is.gd/xKJM5c (wikipedia) [2012-05-30 08:43:32]
57. [python] pexpect 这样的神器，windows是无法享有了（除非在Cygwin上）
    http://www.noah.org/wiki/Pexpect#pty_module [2012-05-30 20:04:25]
58. [python] pexpect 对多线程有着良好的支持 http://is.gd/DLsIy9 (IBM developerWorks) [2012-05-30
    20:05:38]


