
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2012-09
  :PROPERTIES:
  :PAGE:     ing/2012-09.html
  :ARCHIVE_TIME: 2014-01-11 六 14:19
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. bug of cyg-apt: # cyg-apt -d install cygwin\nwarning: missing packages: _autorebase\n/setup/http%3a%2f%2fmirrors.163.com%2fcygwin/release/_autorebase/_autorebase-000121-1.tar.bz2\n1391f0a95b718dabffa2dbeb03e4b948 _autorebase-000121-1.tar.bz2\n1391f0a95b718dabffa2dbeb03e4b948 _autorebase-000121-1.tar.bz2 [2012-09-02 22:20:38]
2. 领导老问我们”你们做这个架构，有什么能说明是缺了你不行的？“，刚才看见【外刊IT评论网】这篇《超级程序员神话》说到这个问题：只有编写真正有难度东西的才是“真正的程序员”吗? "当问题被分解成更小的问题后，所有的问题都变得如此简单，而且所有的问题都能这样去分解" http://www.aqee.net/the-myth-of-the-super-programmer/ [2012-09-03 10:35:48]
3. [todo] python-mode邮件列表里有人贴出了对pycomplete的改进，嗯，我得把它合入eepy里面去http://is.gd/MrQaqA http://is.gd/bcXBTc [2012-09-03 11:20:34]
4. RT @cuixueqin: 方校长罹患直肠癌，就相当于正常的直肠肛门排便＂连接被重置＂，只好通过人工造瘘的方式走代理了。真心祝愿像网友们体验过的VPN挂掉一样，方校长以后也有机会尝到关键时刻代理失效的滋味。[2012-09-05 11:50:28]
5. 这东西不错：python-mode for vim, 集成了pylint/pyflakes、rope等诸多功能，算是把vim变成个python ide了 https://github.com/klen/python-mode [2012-09-05 11:51:38]
6. "当前的包管理工具链是 easy_install/pip + distribute/setuptools + distutils, 显得较为混乱。而将来的工具链组合非常简单：pip + distutils2 " - Python 包工具之间的关系http://blog.yangyubo.com/2012/07/27/python-packaging/ [2012-09-05 15:44:11]
7. pyflymake.bat欲调用其所在目录下的pyflymake.py，里面得这么写: @python %~dpn0.py %* 这个~dpn0太难记了 [2012-09-05 17:46:56]
8. RT @ Funpea : 每次按下电脑的开机键后，会有足够的时间去泡一杯咖啡，咖啡泡好了，Windows也差不懂启动完成了。这就是微软的人性化之处了，其实这是让我们要懂得抓紧时间享受生活，不像苹果那些快速启动的设计，连泡杯咖啡的时间都没有，实在是很没品位的设计。 [2012-09-06 13:13:15]
9. evernote web clipper越来越鸡肋了，老是报告说我没登录，又不自动跳出登录界面——我也找不到在哪里登录，转到网站去登录还会导航到那个死慢的主界面。总之不如那个bookmarklet，轻量级，还跨浏览器、跨平台[2012-09-10 13:42:26]
10. 用暴力法+手工操作数据库的方法，终于在Redmine-1.4上搞定了checkout插件 [2012-09-11 09:31:39]
11. Another alternative is to use mingw-get to install "the console2 installer" msys-console.  Then, you run the /usr/bin/console-config script and it will download, configure, install (and, if [2012-09-11 09:50:52]
12. mintty is great, and I use it all the time with cygwin. But there is one big drawback (google "cygwin pty native applications" for an explanation).  console2 doesn't have that problem, [2012-09-11 09:51:27]
13. Another alternative is to use mingw-get to install "the console2 installer" msys-console.  Then, you run the /usr/bin/console-config script and it will download, configure, install (and, if all goes well) create a shortcut for you all in one step... [2012-09-11 09:52:09]
14. mintty is great, and I use it all the time with cygwin. But there is one big drawback (google "cygwin pty native applications" for an explanation).  console2 doesn't have that problem, which is far more prevalent in the msys/mingw milieu than in cygwin.  http://is.gd/DdAQdH [2012-09-11 09:52:35]
15. RT @郭敬明: 你们就当我是中国的脑残粉好了。我就是曾经在天安门看升国旗哭了的人，我就是每次看奥运听见国歌就眼红哽咽的人，我就是曾经半夜看网上北京奥运圣火传递时，中国人保护火炬的图片，看得嚎啕大哭的人。你们不用怀疑，这种人是存在的。我的祖国确实有很多问题，但这并不影响我毫无保留地爱它，为它自豪。 [2012-09-11 11:48:58]
16. github这种network graph功能真是好啊，一看就可以看出有人对bartab做了一些改进: https://github.com/fhoech/BarTab/network [2012-09-11 18:00:50]
17. PuTTY as local MSYS terminal? http://is.gd/DdAQdH 在ConEmu的作者冒出来之后，这个帖子歪楼了。ConEmu的作者很热心这个啊，从Whats New里面能看出来针对这个做了改进，好事http://code.google.com/p/conemu-maximus5/wiki/Whats_New [2012-09-12 09:09:38]
18. RT @EnzorZ: 上海将排查疑似精神病患者“无故不上学、不上班、不出家门、不和任何人接触”、“对人过分冷淡，寡言少语、动作慢、什么事情都不做，甚至整天躺在床上”、“过分话多、活动多，到处乱跑，乱管闲事等”。神回复是：第一条说的She，第二条说的who，第三条说的when [2012-09-14 08:07:35]
19. 用vnc访问debian里面的xfce桌面，发现终端里不能用tab键补全，敲了之后窗口只是会闪一下，我只能用Ctrl-I来替代。最后实在不爽了，谷歌了一下，居然说是xfwm里面默认将<super>Tab占用了http://blog.zerosum42.com/2011/10/tech-fixing-tab-key-in-vnc.html [2012-09-17 10:17:35]
20. 在putty里跑emacs时如何得到更多颜色: 1)putty里面设置Allow terminal to use xterm 256-colour mode 2)export TERM=xterm-256color 3)启动emacs后用M-x list-color-display检查。 如果不成功，按EmacsWiki上的描述排查一下吧 http://emacswiki.org/emacs/PuTTY#toc2 [2012-09-17 12:10:11]
21. RT @ruffchen: 家住朝阳区的郝先生近来迷上了陌陌交友。不久前的一个深夜，他在陌陌上发现了一位附近的女网友。短暂交谈后，他发现这是一个善良美丽的女孩。更难能可贵的是，女孩十分纯洁，对约炮、一夜情、包养等话题毫无兴趣。郝先生不由得暗自赞叹“这样的好女孩太少了！”，并最终鼓起勇气，果断… [2012-09-18 08:36:24]
22. 让nginx重新加载配置文件: /opt/nginx/sbin/nginx -s reload [2012-09-18 16:01:35]
23. git protocol(git://...)是只读的?  (BTW: 这篇博客是在乱说，其实他把协议换成ssh了: http://is.gd/ku6dAr ) [2012-09-19 11:55:17]
24. `screen -U` runs in UTF-8 mode. This option tells screen that your terminal sends and understands UTF-8 encoded characters. It also sets the default encoding for new windows to `utf8'. [2012-09-20 14:42:40]
25. Don’t Like Firefox’s Save Per Site Download Feature? Fix It: user_pref("browser.download.lastDir.savePerSite", false) http://is.gd/LF23K7 [2012-09-20 15:24:19]
26. 前两天刚将Debian New Packages http://packages.debian.org/sid/newpkg 订阅到了Google Reader, 还是怎么没什么新软进入Debian 呢，结果今天kernel 3.2.0-4进来，一下800多个包，GR被刷屏了 :-( [2012-09-21 13:07:00]
27. Gitorious 2.3 released: Repository paths are no longer hashed/sharded by default, but stored in plaintext format. TNND, 前几天白研究了http://blog.gitorious.org/2012/09/20/gitorious-2-3-released/ [2012-09-21 13:48:53]
28. 将firefox升到v15之后，书签那个星星不能打开编辑对话框了（用来编辑书签详细内容），通过二分法定位，居然是Compact Menu 2这个扩展导致的，AMO网站上说 Yes, this extension on AMO currently breaks a number of basic bookmarking features. [2012-09-22 11:47:19]
29. 续: 装这个版本的Compact Menu 3可以解决上述问题 http://franklion.co.uk/CMB.html [2012-09-22 11:50:34]
30. The interesting part is that these systems (git/hg) think in terms of changes, not in terms of versions.That’s a very zen-like thing to say, I know... http://www.joelonsoftware.com/items/2010/03/17.ht [2012-09-22 13:13:38]
31. ... Traditional version control thinks: OK, I have version 1. And now I have version 2. And now I have version 3. And distributed version control thinks, I had nothing. And then I got these changes. A [2012-09-22 13:14:16]
32. Joel Spolsky选择了使用mercurial（而不是git），这是他写的教程: Hg Init: a Mercurial tutorial http://hginit.com/ [2012-09-22 13:18:52]
33. Joel Spolsky在twitter上说了一句: religious git/mercurial arguments never get anywhere, and they're dumb. 嗯，说得对，我不要再纠结这个问题了。 [2012-09-22 13:31:00]
34. RT @elaoda 如果你非得使用QQ，那么安装完QQ必须要删除掉的几个恐怖文件 ： QQExternal、XPlatform、TXPFProxy.dll 这三个文件（直接Shift + Delete 键删除，不必入回收站） [2012-09-22 14:59:35]
35. 每次VirtualBox出新版本，我都要下载下来，把我那几个linux虚拟机跑一下，看还能起来不（原来老卡在启动上，报kernel panic）。这次4.2上面终于能跑了，搜了一下闪存，出现问题是在2011-09-15，然后就一直不能用，都一年了，吐血 [2012-09-22 16:37:19]
36. 想查查我的evernote3里面的数据是不是都迁移到evernote4了（因为原来迁移后又在v3上加了些笔记），一个个比对太累了，鉴于它的数据库是sqlite，于是简单写个python脚本来搞 https://gist.github.com/3774144 [2012-09-24 12:07:23]
37. evernote 4.x的数据库里，笔记是直接存放在note_attr里面的，笔记的各个属性都有对应字段；而evernote 3.x不是，网上看到evernote论坛一个帖子里面透露了些信息: http://is.gd/APBd31 [2012-09-24 12:13:36]
38. 简单地说，evernote3里，笔记信息是存放在attrs表里的，uid为笔记id，而一则笔记的多个属性分存在attrs多条记录里，aid=0的记录其data中存放的是笔记标题, aid=15则data中存放的是笔记正文，aid=44则data中存放的是source url ，而tag还不知道在哪里 [2012-09-24 12:16:23]
39. gedit的windows版本缺少一个libglade2.0-0.dll，导致grep插件不能用，可从这里下载一份(gedit-2.30需要的是libglade-2.6) http://ftp.gnome.org/pub/GNOME/binaries/win32/libglade [2012-09-24 15:57:38]
40. gedit的windows版本带了ipython插件，但还得自己安装ipython才行，从其它地方拷贝python26.exe, pythonw26.exe到gedit/bin目录，注册表里添加 HKLM\SOFTWARE\Python\PythonCore\2.6\InstallPath @="{path\to\gedit\bin}" 然后就可以运行ipython安装程序来安装了 [2012-09-24 16:00:38]
41. 续: gedit的ipython插件里调了import gconf，但gedit的win32安装包并没有包含python-gconf，我没有找到python-gconf的win32二进制包，于是把该插件里面的gconf相关代码注释了（其实只用来取了一下gedit或gnome的字体设置） [2012-09-24 16:05:02]
42. gedit才是linux上的notepad++啊 https://live.gnome.org/Gedit/Plugins [2012-09-25 08:59:33]
43. gedit(2.30)的win32版本是从 %APPDATA%/gedit/plugins 目录加载用户的插件，但配置数据却写到~/.gnome2/gedit 这个目录——有的第三方插件还写到别的目录 [2012-09-25 12:04:05]
44. 【A股与A片的9个共同点】1、都令人亢奋；2、上下幅度都很大；3、对大多数人有害；4、必要时都用嘴来吹捧；5、诱人达到高潮后一泻千里；6、都会做俯卧撑；7、长阳时间都很短；8、搞来搞去都是为了出货；9、多数人不喜欢带套，但还是都套上了！和谐一下！ [2012-09-26 06:10:28]
45. 1785楼左三，好像我儿子 http://is.gd/g6s8qJ :-) [2012-09-26 13:16:23]
46. MongoDB 吐槽汇总贴 Does everyone hate MongoDB?  http://is.gd/G5ZNu5 (serverdensity.com) [2012-09-27 09:33:39]


