
Archived entries from file /users/bamanzi/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org

* 2012-02
  :PROPERTIES:
  :PAGE:     ing/2012-02.html
  :ARCHIVE_TIME: 2014-01-11 六 14:18
  :ARCHIVE_FILE: ~/projects/bamanzi.bitbucket.org/CNBlogs_Ing.org
  :ARCHIVE_CATEGORY: CNBlogs_Ing
  :END:

1. [工具软件] alternativeto.net 这个网站真是不错，可以很方便地看看某个软件有没有更好的替代品，比如刚
   才从 http://alternativeto.net/software/miniMiZE 看到miniMIZE的一个替代品ThumbWin，不过也不能选择
   性地最小化 [2012-02-01 10:28:02]
2. [wxpython] 原来pyslices已经提供了方法切换为默认单行输入/Ctrl+Enter多行输入的选项了，就在菜单
   Options->Settings->Enable Shell Mode [2012-02-01 10:33:38]
3. [dropbox] 『只要你使用最新版本Dropbox的相片匯入功能（目前版本是1.3.12），首次使用即時送你500MB空
   間，然後每上載500MB就再送500MB，最高送4.5GB（即共5GB）』 http://infilmity.com/685.php [2012-02-03
   12:01:55]
4. [linux] sudo add-apt-repository ppa:freefilesync/ffs && sudo apt-get install freefilesync
   http://www.webupd8.org/2012/02/compare-and-synchronize-folders-with.html [2012-02-04 17:09:51]
5. [linux] marlin file manager: sudo add-apt-repository ppa:marlin-devs/marlin-daily && sudo
   apt-get install marlin
   http://maketecheasier.com/using-marlin-file-manager-as-nautilus-alternative/2012/02/02
   [2012-02-04 17:10:44]
6. [linux] Ubuntu One Indicator: Manage Ubuntu One Synchronization From System Tray $ sudo
   add-apt-repository ppa:rye/ubuntuone-extras && sudo apt-get install ubuntuone-indicator
   http://www.wmlcloud.com/linux/ubuntu-one-indicator-manage-ubuntu-one-synchronization-from-system-tray/
   [2012-02-04 20:07:47]
7. [linux] 前面那个marlin仓库不支持natty，只支持natty之后的版本(11.10及以后) [2012-02-05 14:11:16]
8. [工具软件] 这个QTranslator小工具不错，可以将选中文字通过Google Translator, Yahoo BabelFish等服务进
   行翻译、朗读 [2012-02-07 09:41:04]
9. 刚用Firefox自带的开发工具解决了一个小问题: portablefreeware.com 通过meta refresh前转到
   qtranslator网站，但 appspot.com 被墙，通过这个工具看到了目的地址 [2012-02-07 10:53:10]
10. 简单的软件部署，不妨直接调用ssh，而fabric这个python库/工具应该有些帮助 http://www.fabfile.org/
    [2012-02-07 11:39:17]
11. Just found this: #vim emulation for Total Commander !  http://sf.net/p/viatc open souce and
    written in #autohotkey [2012-02-07 11:46:42]
12. 这份Git简易指南 http://rogerdudler.github.com/git-guide/index.zh.html 中将缓存区表述为index
    tree，总让人感到迷惑，pro git里说这叫stagine area，还是后面这个说法比较直观 [2012-02-07
    15:39:18]
13. 『运行了 git add 之后又作了修订的文件，需要重新运行 git add 把最新版本重新暂存起来』 [2012-02-07
    16:30:47]
14. [emacs] TNND, semantic-tag-folding 在Emacs 24里面的semantic 下又不能用了，因为后者修改了
    semantic-add-minor-mode的接口 [2012-02-07 17:03:03]
15. [emacs] 不知不觉间，cedet-1.0.1已经发布了，从1.0到1.0.1用了近一年半——当然，更别说之前的beta版，从
    beta1到最后1.0发布，用了差不多7年 [2012-02-07 17:17:31]
16. 看见cedet-1.0.1里面添加了对sxemacs的支持，以为这是个新fork，刚才翻到它的News页面才发现，它在04年
    就有了 [2012-02-08 09:03:38]
17. sxemacs的screenshots里面没一个是关于编辑代码的，都是irc, term, calender以及游戏什么的，只有那个
    LiveJournal跟“编辑器”两字有点关系 http://www.sxemacs.org/screenshots.html [2012-02-08
    09:10:27]
18. python脚本转可执行程序的工具有: py2exe; py2app; PyInstaller; cx_Freeze; bbFreeze; 试用了前面4个，
    目前觉得cxfreeze比较适合简单脚本，因为生成的是单个文件（除了需要python27.dll之外)，而py2exe和
    py2app会拷贝一堆文件（包括一个library.zip），还需要编写setup.py [2012-02-08 18:08:14]
19. [todo] keysnail: <f5> b/B, goo.glx, C-x m [2012-02-08 18:11:00]
20. [emacs] eshell里面调用命令行编译、搜索的话，可以打开compilation-shell-minor-mode，这样可以很容易
    跳转到相应文件(以及对应行). compilation-minor-mode也行——我看了elisp代码，这两者除了hook不一样，没
    有什么区别（而且两者的hook实际上都没定义(不存在)) [2012-02-09 13:55:20]
21. [emacs] eshell里面如果想调用外部grep程序（缺省是转给elisp函数grep或者eshell/grep）的话，得在前面
    加星号 (见eshell-explicit-command-char变量设置) [2012-02-09 13:57:53]
22. [far] 仔细看了一下FAR的帮助（不能查找文字实在是不爽，只得拷出来查找），原来可以传入另一面板的路径、
    文件，不过跟totalcmd不同，不是新的特殊符号，而是两个修饰符!#和!^，分别表示这之后的就采用另一面板
    (或当前面板）的值，比如!#!\!.!表示另一面板下的当前文件，!#!\!^!.!表示另一面板下跟当前面板选中项同
    名的文件 [2012-02-10 12:05:31]
23. [far] 这个Visual Compare可以用来做目录、文件的比较
    http://code.google.com/p/far-plugins/wiki/VisualCompare 想直接在面板中启动单个文件比较的话，可以
    在User menu里面配一个vc: !.! !#!\!.!  注意!.!本身只包含文件名，不包含路径，得加!\ [2012-02-10
    12:08:44]
24. [far] Visual Compare还支持svn的比较: "vc:svn: ."将当前目录与svn base相比较，不过还不知
    道怎么比较单个文件 [2012-02-10 12:11:12]
25. [emacs] [orgmode] Can I use the editing features of org-mode in other modes?
    http://orgmode.org/worg/org-faq.html#use-editing-features-in-other-modes orgtbl-mode,
    orgstruct-mode, org-footnote-action & org-cycle [2012-02-10 15:12:00]
26. [far] 读读帮助还是有用嘀，刚又学了两个快捷键: 1)Alt-Ins开始选中屏幕上的文字，移动光标到开始位置，
    按Shift移动光标选择，回车拷贝；2)对于菜单和列表，按Ctrl-Alt-F进入过滤方式（可惜对文件列表不管
    用:-( ） [2012-02-13 09:41:28]
27. [far] 用了二分定位法，发现FAR不能用右键选择文件的问题是MacroLib插件引起的，在改插件的Options里面
    取消process mouse就可以了 [2012-02-13 11:12:21]
28. [far] 一直觉得FAR欠缺一个动态过滤功能，它有一个Filter设置(Commands->File panel filter C-I)，但
    每次进去设置太繁琐了，没法用来即时找文件。今天发现MacroLib里面包含了一个FastFilter宏，装上之后按
    住右Alt再按字母键就是即时(增量式)过滤，按两下右Alt就清除，右Alt-/可以直接输入，其实实现上是调用了
    Ctrl-I那个对话框的功能 http://code.google.com/p/far-macro-library/wiki/Shell_FastFilter
    [2012-02-13 15:33:34]
29. 突然在别人的代码库里面发现自己当年写的一个小脚本devhelp2chm
    http://htmlhelp.googlecode.com/svn/trunk/misc/devhelp2chm.sh [2012-02-14 09:18:01]
30. [emacs][python] loveshack这个版本的python.el包含了python-compilation-regexp-alist 设置，可用在
    compile/shell中, 且支持路径中带空格 http://www.loveshack.ukfsn.org/emacs/python.el [2012-02-14
    12:06:14]
31. [emacs][python] compile-mode error navigation through the python stack trace of a unittest
    failure http://is.gd/50CMDs [2012-02-14 15:56:01]
32. [emacs][python] Emacs: Compilation mode and error navigation - IDEIntegration - SCons Wiki
    http://www.scons.org/wiki/IDEIntegration#Compilation_mode_and_error_navigation [2012-02-14
    17:48:13]
33. [emacs] TNND, 新版anything-config.el把缺省触发键从<f5> a改成C-x c了，刚才我说怎么都不能激活
    anything了 [2012-02-15 10:56:20]
34. [firefox][addons] panolink 跟pano不兼容啊，都使用chrome://pano/ 目录空间，打架了，手工改改吧
    [2012-02-17 08:38:33]
35. 深圳FM 105.7 每天中午13:00 锵锵三人行 [2012-02-17 13:59:15]
36. [firefox][hacking] TGM不支持AppTabs, 又切回pano了, 但有点想念TGM的hibernate功能, 在AMO网站上找了
    一圈没找到替代品（snap ponorama本来还凑合，但我不想存入书签（不想被同步）），最后修改了一下
    tabundle（从全部存改为只存当前group的内容），但没有全部恢复的办法——或者修改一下TMT? [2012-02-17
    13:59:25]
37. 这个spacefm是从pcmanfm分支出来的一个文件管理器，最多4个面板，多标签页，用来移动、拷贝文件还挺方
    便，最大的问题是界面的拼凑感比较强，功能有点乱 http://spacefm.sourceforge.net/ [2012-02-18
    11:31:14]
38. 一直认为gedit的定位是个普通文本编辑器，代码编辑、程序功能比较弱，结果昨天在youtube上看到gedit as
    python ide的视频，然后又在google code上搜了一下，发现这家伙的插件比geany多多了
    http://code.google.com/hosting/search?q=label:gedit [2012-02-20 18:13:25]
39. [firefox][addons] 用proxy selector替代了toggle proxy，因为前者支持多个proxy之间切换，而后者只支持
    两个 [2012-02-21 09:35:19]
40. 13911463436 朱先生 苏州街 西屋国际C座1102 [2012-02-21 21:11:48]
41. What IDE to use for Python? - Stack Overflow -
    http://stackoverflow.com/questions/81584/what-ide-to-use-for-python 从功能支持的全面程度来说，也
    就Emacs, PyDev, NetBeans, Komodo, Vim这几个选择，不考虑跨平台的话还有ScriptDev和PTVS [2012-02-21
    22:25:55]
42. [firefox] 『GreaseMonkey 脚本：Markdown textarea，此脚本会在文本域的左下角新增一个 Markdown 按
    钮，输入各种包含 Markdown 的文字之后，点击它就可以把代码转化为为 HTML 』
    http://userscripts.org/scripts/show/91369 [2012-02-23 09:03:46]
43. ReText is a simple but powerful text editor for Markdown and reStructuredText. (written in
    python + qt) http://sourceforge.net/p/retext/home/ReText/ [2012-02-23 09:16:53]
44. [g_f_w] google plus还可以直接上了 [2012-02-24 08:45:04]
45. sugarsync: Sync doesn't work in folders below an NTFS junction http://is.gd/dULptz
    [2012-02-25 22:58:48]
46. A simple plugin system for Python applications http://yapsy.sourceforge.net/ [2012-02-25
    23:57:40]
47. Linux下创建wifi热点太简单啦，XP下我弄了一小时没搞定，LinuxMint下一分钟就搞定了: Create a wifi
    hotspot using my desktop - Ask Ubuntu http://is.gd/AJkKnD [2012-02-26 21:16:17]
48. 屌丝：一个字头的诞生_评论频道_凤凰网 - http://news.ifeng.com/opinion/special/diaosi/ [2012-02-27
    23:44:58]
49. 今天才知道“碉堡了”是“屌爆了”的意思 [2012-02-28 10:09:55]
50. python v.s. java http://almaer.com/blog/uploads/dynamicstatic.png [2012-02-28 22:36:31]
51. cygwin setup.exe command line arguments http://cygwin.com/faq/faq.setup.html#faq.setup.cli
    [2012-02-29 20:32:08]


